import { desc, eq, sql } from "drizzle-orm";
import { NextRequest, NextResponse } from "next/server";
import { getDb } from "../../../db";
import { auditEvents, dataDictionaryItems, dataSharingAgreements, governanceDatasets, governanceDecisions, governanceInstitutions, governanceWorkflows, integrationExchanges } from "../../../db/schema";

export const dynamic="force-dynamic";
const today="2026-08-02";
const institutions=[
  ["MOA","Ministry of Agriculture","Lead institution and official owner of national agricultural data and services.","Lead data owner",["Farmer and farm registry","Production and value chains","Agricultural programmes","Publication approval"]],
  ["MGCSP","Ministry of Gender, Children and Social Protection","Social protection, gender equality, vulnerability and beneficiary validation.","Social protection validator",["Household vulnerability","Social protection participation","Gender and inclusion","Beneficiary validation"]],
  ["CDA","Cooperative Development Agency","Certification, profiling and strengthening of cooperatives and farmer organizations.","Cooperative certifier",["Cooperative certification","Organization governance","Membership records","Compliance status"]],
  ["LISGIS","Liberia Institute of Statistics and Geo-Information Services","Statistical standards, geospatial reference data, boundaries and national harmonization.","Statistical and GIS authority",["Data classifications","Administrative boundaries","Geospatial quality","Survey harmonization"]],
  ["LOCAL","County, District and Community Authorities","Validated local contributions, field confirmation, endorsement and escalation.","Local endorsing authority",["Community submissions","Farm location endorsement","Production updates","Local corrections"]],
] as const;
async function seed(){const db=await getDb();if(!(await db.select({id:governanceInstitutions.id}).from(governanceInstitutions).limit(1)).length){
  await db.insert(governanceInstitutions).values(institutions.map(x=>({institutionCode:x[0],name:x[1],mandate:x[2],accountRole:x[3],contentResponsibilities:JSON.stringify(x[4])})));
  await db.insert(governanceDatasets).values([
    {datasetCode:"DFR-FARMER",title:"National Farmer & Farm Master Registry",domain:"Agriculture",ownerInstitution:"MOA",stewardInstitution:"MOA",custodianInstitution:"MOA ICT",approvingAuthority:"MOA Chief Data Officer",sensitivity:"Restricted",accessRule:"Purpose-bound role and geographic scope",classificationStandard:"DFR Core v1.2",lastReviewedAt:"2026-07-15",nextReviewAt:"2026-10-13",metadata:JSON.stringify({retention:"Active + 10 years",quality:"98.1%"})},
    {datasetCode:"DFR-VULN",title:"Household Vulnerability & Social Protection",domain:"Social protection",ownerInstitution:"MGCSP",stewardInstitution:"MGCSP",custodianInstitution:"DFR Operations",approvingAuthority:"MGCSP Director",sensitivity:"Highly restricted",accessRule:"Explicit purpose, minimum fields, logged access",classificationStandard:"National Social Registry mapping v0.9",lastReviewedAt:"2026-04-01",nextReviewAt:"2026-06-30",metadata:JSON.stringify({stale:true,quality:"Pending review"})},
    {datasetCode:"DFR-COOP",title:"Cooperatives & Producer Organizations",domain:"Organizations",ownerInstitution:"CDA",stewardInstitution:"CDA",custodianInstitution:"MOA Registry Unit",approvingAuthority:"CDA Registrar",sensitivity:"Official-use",accessRule:"Organization verification roles; public summary only",classificationStandard:"CDA Cooperative Profile v1.0",lastReviewedAt:"2026-07-12",nextReviewAt:"2026-10-10",metadata:"{}"},
    {datasetCode:"DFR-GEO",title:"Administrative Boundaries & Farm Parcels",domain:"Geospatial",ownerInstitution:"LISGIS",stewardInstitution:"LISGIS",custodianInstitution:"MOA GIS Unit",approvingAuthority:"LISGIS Geo-Information Director",sensitivity:"Restricted",accessRule:"Generalized public view; exact parcels controlled",classificationStandard:"WGS84 / EPSG:4326; GeoJSON",lastReviewedAt:"2026-06-20",nextReviewAt:"2026-09-18",metadata:JSON.stringify({topology:"LISGIS QA profile"})},
  ]);
  await db.insert(governanceWorkflows).values([
    {caseId:"CDA-VER-00041",workflowType:"CDA cooperative certification",subjectRef:"ORG-LR-2026-0041",title:"Foya Cocoa & Rice Farmers Cooperative",submitterInstitution:"MOA",currentInstitution:"CDA",stage:"UNDER_REVIEW",dueDate:"2026-08-07",county:"Lofa",evidenceRef:"CDA certificate, bylaws, officer register"},
    {caseId:"MGCSP-VAL-00118",workflowType:"MGCSP vulnerability validation",subjectRef:"HH-LR-00118",title:"Household vulnerability and beneficiary validation",submitterInstitution:"LOCAL",currentInstitution:"MGCSP",stage:"SUBMITTED",dueDate:"2026-08-05",county:"Bong",evidenceRef:"Consent, household roster, field assessment"},
    {caseId:"LISGIS-QA-00027",workflowType:"LISGIS geospatial approval",subjectRef:"PARCEL-LR-00027",title:"Parcel boundary and topology quality approval",submitterInstitution:"MOA",currentInstitution:"LISGIS",stage:"CORRECTION_REQUESTED",decision:"Correction required",notes:"Resolve overlap at north-west vertex.",dueDate:"2026-08-04",county:"Nimba",evidenceRef:"GeoJSON, GPS accuracy report"},
    {caseId:"LOCAL-END-00076",workflowType:"Community contribution endorsement",subjectRef:"DFR-LR-00076",title:"Community-submitted farmer profile endorsement",submitterInstitution:"Community focal person",currentInstitution:"LOCAL",stage:"APPROVED",decision:"Endorsed",dueDate:"2026-08-03",county:"Grand Bassa",evidenceRef:"Community attestation and field photo"},
  ]);
  await db.insert(dataDictionaryItems).values([
    {elementCode:"DFR.PERSON.SEX",name:"Sex",definition:"Sex of the registered person as reported and validated.",domain:"Demographic",dataType:"Code",allowedValues:JSON.stringify(["Female","Male","Intersex","Not stated"]),standardOwner:"LISGIS",version:"1.1",effectiveDate:"2026-07-01"},
    {elementCode:"DFR.HH.VULN",name:"Vulnerability classification",definition:"Approved household vulnerability category used for targeting.",domain:"Social protection",dataType:"Multi-code",allowedValues:JSON.stringify(["Female-headed","Youth","Disability","Shock-affected","Food insecure"]),standardOwner:"MGCSP",version:"1.0",effectiveDate:"2026-07-01"},
    {elementCode:"DFR.GEO.COUNTY",name:"County code",definition:"Official county classification for Liberia.",domain:"Geospatial",dataType:"Code",allowedValues:JSON.stringify(["Bomi","Bong","Gbarpolu","Grand Bassa","Grand Cape Mount","Grand Gedeh","Grand Kru","Lofa","Margibi","Maryland","Montserrado","Nimba","River Cess","River Gee","Sinoe"]),standardOwner:"LISGIS",version:"2026.1",effectiveDate:"2026-01-01"},
  ]);
  await db.insert(dataSharingAgreements).values([
    {agreementCode:"DSA-MOA-MGCSP-001",title:"Agriculture–social protection minimum-data exchange",providerInstitution:"MOA",recipientInstitution:"MGCSP",datasets:JSON.stringify(["DFR-FARMER","DFR-VULN"]),purpose:"Eligibility referral and beneficiary validation",legalBasis:"Approved inter-ministerial data-sharing protocol",sensitivity:"Highly restricted",accessProtocol:"OAuth 2.0 + mTLS; field minimization; immutable logging",effectiveDate:"2026-07-01",expiryDate:"2027-06-30",status:"Draft for signature",reviewDate:"2026-10-01"},
    {agreementCode:"DSA-MOA-LISGIS-002",title:"Geospatial standards and boundary quality exchange",providerInstitution:"LISGIS",recipientInstitution:"MOA",datasets:JSON.stringify(["DFR-GEO"]),purpose:"Boundary reference and parcel quality assurance",legalBasis:"Government statistical and geospatial mandate",sensitivity:"Restricted",accessProtocol:"Signed GeoJSON packages and controlled API",effectiveDate:"2026-06-15",expiryDate:"2027-06-14",status:"Active",reviewDate:"2026-09-15"},
  ]);
  await db.insert(governanceDecisions).values([
    {decisionCode:"DGC-RES-2026-008",meetingType:"Data Governance Committee",title:"Adopt minimum-data principle for vulnerability exchange",decisionText:"Only approved eligibility attributes may be exchanged with programme systems.",responsibleInstitution:"MOA/MGCSP",actionOwner:"Data Protection Working Group",meetingDate:"2026-07-28",dueDate:"2026-08-14",priority:"High",status:"In progress",escalationLevel:"Committee"},
    {decisionCode:"GIS-WG-2026-014",meetingType:"Geospatial Working Group",title:"Approve LISGIS boundary release 2026.1",decisionText:"Use release 2026.1 as authoritative administrative reference after topology validation.",responsibleInstitution:"LISGIS",actionOwner:"MOA GIS Unit",meetingDate:"2026-07-30",dueDate:"2026-08-07",priority:"Normal",status:"Open",escalationLevel:"Working group"},
  ]);
  await db.insert(integrationExchanges).values([
    {connectorCode:"CONN-NSR",systemName:"National Social Registry",ownerInstitution:"MGCSP",direction:"Bidirectional",endpointAlias:"NSR beneficiary exchange",standard:"REST/JSON · OpenAPI 3.1",mappingVersion:"0.9",environment:"Configuration",status:"Awaiting endpoint",result:"No live exchange attempted",correlationId:"CFG-NSR-001"},
    {connectorCode:"CONN-CENSUS",systemName:"National Census & Survey Data",ownerInstitution:"LISGIS",direction:"Inbound",endpointAlias:"LISGIS statistical exchange",standard:"REST/JSON + CSV package",mappingVersion:"1.0",environment:"Sandbox",status:"Mapping validated",lastTestedAt:"2026-07-31",records:250,result:"Schema validation passed",correlationId:"TEST-LISGIS-250"},
    {connectorCode:"CONN-CDA",systemName:"CDA Cooperative Certification",ownerInstitution:"CDA",direction:"Bidirectional",endpointAlias:"CDA verification adapter",standard:"REST/JSON · OpenAPI 3.1",mappingVersion:"1.0",environment:"Configuration",status:"Awaiting endpoint",result:"Workflow operational; external endpoint pending",correlationId:"CFG-CDA-001"},
  ]);
  await db.insert(auditEvents).values({actor:"Institutional Governance",action:"Governance control framework initialized",entity:"National DFR",details:"Institution accounts, stewardship, approval workflow, metadata, agreements and exchange controls established"});
}return db}
const parse=(x:string,fallback:any)=>{try{return JSON.parse(x)}catch{return fallback}};
export async function GET(){const db=await seed();const [i,d,w,dd,a,dec,x,audit]=await Promise.all([db.select().from(governanceInstitutions),db.select().from(governanceDatasets),db.select().from(governanceWorkflows).orderBy(desc(governanceWorkflows.updatedAt)),db.select().from(dataDictionaryItems),db.select().from(dataSharingAgreements),db.select().from(governanceDecisions).orderBy(desc(governanceDecisions.meetingDate)),db.select().from(integrationExchanges).orderBy(desc(integrationExchanges.createdAt)),db.select().from(auditEvents).orderBy(desc(auditEvents.id)).limit(30)]);return NextResponse.json({institutions:i.map(v=>({...v,contentResponsibilities:parse(v.contentResponsibilities,[])})),datasets:d.map(v=>({...v,metadata:parse(v.metadata,{})})),workflows:w,dictionary:dd.map(v=>({...v,allowedValues:parse(v.allowedValues,[])})),agreements:a.map(v=>({...v,datasets:parse(v.datasets,[])})),decisions:dec,exchanges:x,audit,today})}
const stages=["SUBMITTED","UNDER_REVIEW","CORRECTION_REQUESTED","RESUBMITTED","APPROVED","PUBLISHED"];
export async function PATCH(req:NextRequest){const b=await req.json();const db=await seed();if(b.entityType==="workflow"){
  const current=(await db.select().from(governanceWorkflows).where(eq(governanceWorkflows.id,+b.id)).limit(1))[0];if(!current)return NextResponse.json({error:"Case not found"},{status:404});
  const next=String(b.stage);if(!stages.includes(next))return NextResponse.json({error:"Invalid governance stage"},{status:400});
  await db.update(governanceWorkflows).set({stage:next,decision:b.decision||({APPROVED:"Approved",PUBLISHED:"Published",CORRECTION_REQUESTED:"Correction required"}[next]||"Pending"),notes:b.notes??current.notes,currentInstitution:b.currentInstitution||current.currentInstitution,updatedAt:sql`CURRENT_TIMESTAMP`}).where(eq(governanceWorkflows.id,+b.id));
  await db.insert(auditEvents).values({actor:b.actor||current.currentInstitution,action:`Governance case moved to ${next}`,entity:current.caseId,details:JSON.stringify({from:current.stage,to:next,institution:b.actor||current.currentInstitution,notes:b.notes||""})});return NextResponse.json({ok:true});
}if(b.entityType==="dataset"){
  const row=(await db.select().from(governanceDatasets).where(eq(governanceDatasets.id,+b.id)).limit(1))[0];if(!row)return NextResponse.json({error:"Dataset not found"},{status:404});
  const next=new Date();next.setDate(next.getDate()+row.reviewFrequencyDays);await db.update(governanceDatasets).set({lastReviewedAt:today,nextReviewAt:next.toISOString().slice(0,10),version:b.version||row.version,status:b.status||row.status,updatedAt:sql`CURRENT_TIMESTAMP`}).where(eq(governanceDatasets.id,+b.id));
  await db.insert(auditEvents).values({actor:b.actor||row.stewardInstitution,action:"Dataset stewardship review completed",entity:row.datasetCode,details:`Version ${b.version||row.version}; next review ${next.toISOString().slice(0,10)}`});return NextResponse.json({ok:true});
}return NextResponse.json({error:"Unsupported update"},{status:400})}
