import { and, desc, eq } from "drizzle-orm";
import { NextRequest, NextResponse } from "next/server";
import { getDb } from "../../../db";
import { accessAssignments,auditEvents,benefitIssues,paymentAccounts,paymentTransactions,vouchers } from "../../../db/schema";
import { getChatGPTUser } from "../../chatgpt-auth";
export const dynamic="force-dynamic";
const voucherManagers=new Set(["Voucher administrator","Input-distribution officer","Ministry administrator"]);
const paymentManagers=new Set(["Payment officer","Ministry administrator"]);
async function context(){const user=await getChatGPTUser();if(!user)return null;const db=await getDb();const assignment=(await db.select().from(accessAssignments).where(eq(accessAssignments.email,user.email)).limit(1))[0]||null;const caps:string[]=assignment?JSON.parse(assignment.capabilities||"[]"):[];const role=assignment?.role||"Farmer";return{db,user,role,canVoucher:assignment?.status==="Active"&&(voucherManagers.has(role)||caps.includes("voucher.manage")),canPayment:assignment?.status==="Active"&&(paymentManagers.has(role)||caps.includes("payment.manage"))}}
export async function GET(){const c=await context();if(!c)return NextResponse.json({error:"Authentication required"},{status:401});const allVouchers=c.canVoucher?await c.db.select().from(vouchers).orderBy(desc(vouchers.createdAt)):await c.db.select().from(vouchers).where(eq(vouchers.ownerEmail,c.user.email)).orderBy(desc(vouchers.createdAt));const accounts=c.canPayment?await c.db.select().from(paymentAccounts).orderBy(desc(paymentAccounts.createdAt)):await c.db.select().from(paymentAccounts).where(eq(paymentAccounts.ownerEmail,c.user.email)).orderBy(desc(paymentAccounts.createdAt));const transactions=c.canPayment?await c.db.select().from(paymentTransactions).orderBy(desc(paymentTransactions.createdAt)):await c.db.select().from(paymentTransactions).where(eq(paymentTransactions.ownerEmail,c.user.email)).orderBy(desc(paymentTransactions.createdAt));return NextResponse.json({vouchers:allVouchers,accounts,transactions,access:{role:c.role,currentEmail:c.user.email,canVoucher:c.canVoucher,canPayment:c.canPayment}})}
export async function POST(req:NextRequest){const c=await context();if(!c)return NextResponse.json({error:"Authentication required"},{status:401});const b=await req.json();let entity="";
 if(b.action==="account"){if(!b.farmerDfrId||!b.provider||!b.accountName||!b.accountNumber)return NextResponse.json({error:"Complete all required account fields"},{status:400});const raw=String(b.accountNumber);entity=String(b.farmerDfrId);await c.db.insert(paymentAccounts).values({farmerDfrId:entity,provider:String(b.provider),accountName:String(b.accountName),accountNumberMasked:`${raw.slice(0,4)}•••${raw.slice(-3)}`,ownerEmail:c.user.email,accountType:String(b.accountType||"Mobile money"),status:"Pending verification"});}
 else if(b.action==="voucher"){if(!c.canVoucher)return NextResponse.json({error:"Voucher-management permission required"},{status:403});entity=`VCH-${Date.now().toString(36).toUpperCase()}`;await c.db.insert(vouchers).values({voucherCode:entity,farmerDfrId:String(b.farmerDfrId),ownerEmail:String(b.ownerEmail),programme:String(b.programme),category:String(b.category),value:Number(b.value),currency:String(b.currency||"USD"),expiresAt:String(b.expiresAt),distributionSite:String(b.distributionSite||"To be scheduled"),appointmentAt:String(b.appointmentAt||"")});}
 else if(b.action==="issue"){entity=`ISS-${Date.now().toString(36).toUpperCase()}`;await c.db.insert(benefitIssues).values({issueCode:entity,ownerEmail:c.user.email,subjectType:String(b.subjectType),subjectRef:String(b.subjectRef||"Not yet issued"),category:String(b.category),description:String(b.description)});}
 else return NextResponse.json({error:"Unsupported action"},{status:400});await c.db.insert(auditEvents).values({actor:c.user.email,action:`Benefit workflow ${b.action}`,entity,details:"Identity-attributed action"});return NextResponse.json({ok:true,entity},{status:201})}
export async function PATCH(req:NextRequest){const c=await context();if(!c)return NextResponse.json({error:"Authentication required"},{status:401});const b=await req.json();
 if(b.action==="acknowledge"){const record=(await c.db.select().from(vouchers).where(and(eq(vouchers.voucherCode,String(b.voucherCode)),eq(vouchers.ownerEmail,c.user.email))).limit(1))[0];if(!record)return NextResponse.json({error:"Voucher not found in your account"},{status:404});await c.db.update(vouchers).set({receiptAcknowledged:true}).where(eq(vouchers.voucherCode,record.voucherCode));}
 else if(b.action==="redeem"){if(!c.canVoucher)return NextResponse.json({error:"Distribution permission required"},{status:403});await c.db.update(vouchers).set({status:"Redeemed",redeemedAt:new Date().toISOString()}).where(eq(vouchers.voucherCode,String(b.voucherCode)));}
 else if(b.action==="verify-account"){if(!c.canPayment)return NextResponse.json({error:"Payment permission required"},{status:403});await c.db.update(paymentAccounts).set({status:String(b.status),verified:b.status==="Verified"}).where(eq(paymentAccounts.id,Number(b.id)));}
 else if(b.action==="request-verification"){const account=(await c.db.select().from(paymentAccounts).where(and(eq(paymentAccounts.id,Number(b.id)),eq(paymentAccounts.ownerEmail,c.user.email))).limit(1))[0];if(!account)return NextResponse.json({error:"Account not found in your profile"},{status:404});await c.db.update(paymentAccounts).set({status:"Verification requested",verified:false}).where(eq(paymentAccounts.id,account.id));}
 else if(b.action==="update-account"){const account=(await c.db.select().from(paymentAccounts).where(and(eq(paymentAccounts.id,Number(b.id)),eq(paymentAccounts.ownerEmail,c.user.email))).limit(1))[0];if(!account)return NextResponse.json({error:"Account not found in your profile"},{status:404});const raw=String(b.accountNumber||"");if(!b.provider||!b.accountName||raw.length<7)return NextResponse.json({error:"Complete valid payout details"},{status:400});await c.db.update(paymentAccounts).set({provider:String(b.provider),accountName:String(b.accountName),accountNumberMasked:`${raw.slice(0,4)}•••${raw.slice(-3)}`,status:"Verification requested",verified:false}).where(eq(paymentAccounts.id,account.id));}
 else return NextResponse.json({error:"Unsupported action"},{status:400});await c.db.insert(auditEvents).values({actor:c.user.email,action:`Benefit workflow ${b.action}`,entity:String(b.voucherCode||b.id),details:String(b.status||"")});return NextResponse.json({ok:true})}
