import { desc, eq, sql } from "drizzle-orm";
import { NextRequest, NextResponse } from "next/server";
import { getDb } from "../../../db";
import { getChatGPTUser } from "../../chatgpt-auth";
import { accessAssignments,auditEvents,consentRecords,farmers,monitoringIndicators,operationalControls,qualityAssessments,qualityRules,sopControls } from "../../../db/schema";
export const dynamic="force-dynamic";
const today="2026-08-02";
const caps=["registry.approve","quality.manage","supervision.manage","reports.publish","sop.approve","training.manage","social.referral","governance.manage","recovery.test","access.admin"];
async function context(){const user=await getChatGPTUser();if(!user)return null;const db=await getDb();let a=(await db.select().from(accessAssignments).where(eq(accessAssignments.email,user.email)).limit(1))[0];if(!a){await db.insert(accessAssignments).values({email:user.email,displayName:user.displayName,role:"Ministry administrator",institution:"MOA",reviewedAt:today,capabilities:JSON.stringify(caps)});a=(await db.select().from(accessAssignments).where(eq(accessAssignments.email,user.email)).limit(1))[0]}return{db,user,a,capabilities:JSON.parse(a.capabilities||"[]") as string[]}}
async function ensureSeed(c:NonNullable<Awaited<ReturnType<typeof context>>>){return c.db}
const parse=(v:string,f:any)=>{try{return JSON.parse(v)}catch{return f}};
export async function GET(){const c=await context();if(!c)return NextResponse.json({error:"Authentication required"},{status:401});const db=await ensureSeed(c);const [s,r,q,oc,co,ind,fa,aa]=await Promise.all([db.select().from(sopControls),db.select().from(qualityRules),db.select().from(qualityAssessments).orderBy(desc(qualityAssessments.assessedAt)),db.select().from(operationalControls).orderBy(desc(operationalControls.updatedAt)),db.select().from(consentRecords),db.select().from(monitoringIndicators),db.select().from(farmers),db.select().from(accessAssignments)]);return NextResponse.json({access:{...c.a,capabilities:c.capabilities},sops:s.map(x=>({...x,requiredApprovals:parse(x.requiredApprovals,[]),approvals:parse(x.approvals,[])})),rules:r,assessments:q,controls:oc.map(x=>({...x,details:parse(x.details,{}),evidence:parse(x.evidence,[])})),consents:co.map(x=>({...x,purposes:parse(x.purposes,[])})),indicators:ind,farmers:fa,assignments:aa.map(x=>({...x,capabilities:parse(x.capabilities,[])}))})}
function deny(c:any,cap:string){return !c.capabilities.includes(cap)}
export async function POST(req:NextRequest){const c=await context();if(!c)return NextResponse.json({error:"Authentication required"},{status:401});const db=await ensureSeed(c);const b=await req.json();
 if(b.action==="run-quality") {if(deny(c,"quality.manage"))return NextResponse.json({error:"Not authorized"},{status:403});const rows=await db.select().from(farmers);for(const f of rows){const completeness=[f.firstName,f.lastName,f.gender,f.county,f.district,f.community,f.crop].filter(Boolean).length/7*100;const accuracy=f.latitude&&f.longitude&&f.latitude>=4.15&&f.latitude<=8.75&&f.longitude>=-11.65&&f.longitude<=-7.25?100:70;const scores=[accuracy,completeness,90,f.updatedAt?90:60,88,f.status==="Verified"?100:72].map(Math.round);const overall=Math.round(scores.reduce((a,v)=>a+v,0)/6);await db.insert(qualityAssessments).values({assessmentCode:`DQA-${f.id}-${Date.now()}`,subjectRef:f.approvedDfrId||f.provisionalId||f.dfrId,assessmentType:"Automated six-dimensional screening",accuracy:scores[0],completeness:scores[1],consistency:scores[2],timeliness:scores[3],uniqueness:scores[4],reliability:scores[5],overallScore:overall,outcome:overall>=90?"Passed":overall>=75?"Review":"Correction required",assessedBy:c.user.email})}await db.insert(auditEvents).values({actor:c.user.email,action:"Six-dimensional quality assessment executed",entity:"Farmer Registry",details:`${rows.length} records assessed`});return NextResponse.json({ok:true,count:rows.length})}
 if(b.action==="create-control"){if(deny(c,"governance.manage"))return NextResponse.json({error:"Not authorized"},{status:403});const code=`${String(b.controlType).slice(0,4).toUpperCase()}-${Date.now().toString().slice(-7)}`;await db.insert(operationalControls).values({controlCode:code,controlType:b.controlType,title:b.title,subjectRef:b.subjectRef||"",institution:b.institution||c.a.institution,county:b.county||"National",owner:b.owner||c.user.displayName,reviewer:b.reviewer||"",status:b.status||"Open",priority:b.priority||"Normal",dueDate:b.dueDate,details:JSON.stringify({notes:b.notes||""})});await db.insert(auditEvents).values({actor:c.user.email,action:"Operational control created",entity:code,details:b.title});return NextResponse.json({ok:true,code},{status:201})}
 if(b.action==="record-consent"){const code=`CONS-${Date.now().toString().slice(-8)}`;await db.insert(consentRecords).values({consentCode:code,subjectRef:b.subjectRef,version:b.version||"1.0",language:b.language||"English",purposes:JSON.stringify(b.purposes||["Registry"]),channel:b.channel||"Web",grantedBy:b.grantedBy,status:"Active",grantedAt:today,evidenceRef:b.evidenceRef||""});await db.insert(auditEvents).values({actor:c.user.email,action:"Consent lifecycle record created",entity:code,details:b.subjectRef});return NextResponse.json({ok:true,code},{status:201})}
 return NextResponse.json({error:"Unknown action"},{status:400})}
export async function PATCH(req:NextRequest){const c=await context();if(!c)return NextResponse.json({error:"Authentication required"},{status:401});const db=await ensureSeed(c);const b=await req.json();
 if(b.entity==="sop"){if(deny(c,"sop.approve"))return NextResponse.json({error:"Not authorized"},{status:403});const row=(await db.select().from(sopControls).where(eq(sopControls.id,+b.id)).limit(1))[0];const approvals=parse(row.approvals,[]);if(b.approve&&!approvals.includes(c.a.institution))approvals.push(c.a.institution);await db.update(sopControls).set({stage:b.stage||row.stage,approvals:JSON.stringify(approvals),effectiveDate:b.stage==="PUBLISHED"?today:row.effectiveDate,updatedAt:sql`CURRENT_TIMESTAMP`}).where(eq(sopControls.id,+b.id));await db.insert(auditEvents).values({actor:c.user.email,action:`SOP ${b.stage||"approval"}`,entity:row.sopCode,details:`Institution ${c.a.institution}`});return NextResponse.json({ok:true})}
 if(b.entity==="control"){const row=(await db.select().from(operationalControls).where(eq(operationalControls.id,+b.id)).limit(1))[0];await db.update(operationalControls).set({status:b.status||row.status,evidence:b.evidence?JSON.stringify([...parse(row.evidence,[]),b.evidence]):row.evidence,updatedAt:sql`CURRENT_TIMESTAMP`}).where(eq(operationalControls.id,+b.id));await db.insert(auditEvents).values({actor:c.user.email,action:"Operational control updated",entity:row.controlCode,details:b.status||b.evidence||"Updated"});return NextResponse.json({ok:true})}
 if(b.entity==="consent"){const row=(await db.select().from(consentRecords).where(eq(consentRecords.id,+b.id)).limit(1))[0];await db.update(consentRecords).set({status:"Withdrawn",withdrawnAt:today}).where(eq(consentRecords.id,+b.id));await db.insert(auditEvents).values({actor:c.user.email,action:"Consent withdrawn",entity:row.consentCode,details:row.subjectRef});return NextResponse.json({ok:true})}
 return NextResponse.json({error:"Unknown entity"},{status:400})}
