export const deliverables=[
 {slug:"inception-report",code:"D1",title:"Inception Report",status:"Draft for stakeholder validation",purpose:"Confirms the assignment interpretation, methodology, governance, safeguards, seven-month work plan, quality controls and acceptance process.",sections:[
  ["Executive direction","Establish a secure, interoperable and sustainable national Digital Farmer Registry that supports register-once/use-many service delivery while protecting farmer rights and institutional accountability."],
  ["Methodology","Mobilization and inception; current-state assessment; participatory service and data design; iterative development; controlled integration; testing and pilot; capacity transfer; national rollout preparation; closure and learning."],
  ["Governance","FAO provides contract oversight and acceptance. MoA owns business policy and the registry. MGCSP leads social-protection alignment. LISGIS provides geospatial and statistical standards. County and district authorities support field coordination, verification and adoption."],
  ["Work plan","Month 1 inception and assessment; Month 2 architecture and governance; Months 2–4 software and SOP development; Months 4–5 integration and testing; Months 5–6 training and pilot; Month 7 rollout readiness, lessons and handover."],
  ["Quality and risk","Requirements traceability, privacy-by-design, maker-checker approvals, code review, automated and manual testing, evidence-based acceptance, issue escalation and change control apply to every deliverable."],
  ["Validation required","Final dates, named focal points, workshop calendar, available systems, data-sharing authorities, pilot counties and acceptance signatories require confirmation during inception."]]},
 {slug:"gap-assessment",code:"D2",title:"Gap-Assessment Report",status:"Structured draft—field findings pending",purpose:"Assesses existing registries, social-protection MIS, institutional capacity, data quality, infrastructure, governance and interoperability readiness.",sections:[
  ["Assessment domains","Institutional mandate; registry coverage; farmer and household data; identity controls; GIS; programme delivery; payment and voucher processes; privacy; cybersecurity; infrastructure; skills; support; sustainability."],
  ["Inventory method","For each system record owner, purpose, population, geography, identifiers, data model, technology, hosting, interfaces, legal basis, quality, security, operating cost, support model and reuse readiness."],
  ["Preliminary gaps","Fragmented programme lists, inconsistent identifiers, variable consent records, limited parcel geometry, duplicated beneficiaries, manual verification, weak exchange standards, incomplete retention rules, and uneven subnational connectivity are working hypotheses—not validated findings."],
  ["Scoring","Each capability is scored 0 absent, 1 ad hoc, 2 repeatable, 3 defined, 4 managed, or 5 optimized. Evidence and responsible institution are mandatory for every score."],
  ["Recommendations framework","Prioritize by farmer protection, statutory mandate, service impact, dependency, complexity and cost. Findings become accepted requirements only after institutional validation."],
  ["Pending evidence","System demonstrations, data dictionaries, policies, infrastructure inventories, user interviews, integration specifications and legal review remain required."]]},
 {slug:"system-design",code:"D3",title:"DFR System-Design Document",status:"Technical baseline—approval pending",purpose:"Defines the target business, data, application, integration, security and infrastructure architecture.",sections:[
  ["Architecture principles","Government ownership; open standards; modular services; offline-first field operations; API-first interoperability; privacy and security by design; observability; portability; accessibility; configuration before customization."],
  ["Core domains","Farmer identity, households, farms and parcels, production, cooperatives, programmes, eligibility, extension, vouchers, inputs, payment instructions, grievances, GIS, analytics, users, access, audit and assignment delivery."],
  ["Data design","A stable DFR identifier links versioned farmer, household, farm and programme records. Sensitive identity, financial and location attributes use classification, purpose limitation, field-level authorization and audit logging."],
  ["Integration","A governed API gateway supports social-protection referrals, identity validation, LISGIS geography, payment providers, weather and partner systems. Each interface requires a data-sharing agreement, mapping, security profile, test evidence and operating owner."],
  ["Security","MFA-capable authentication, scoped RBAC/ABAC, encryption in transit and at rest, managed secrets, least privilege, tamper-evident audit, secure development, vulnerability management, incident response, backups and recovery testing."],
  ["Deployment","Containerized services and relational/geospatial storage may run on government-controlled Gen10/Gen11-class infrastructure with redundancy, monitoring, backups and a documented recovery environment."],
  ["Non-functional targets","Availability, recovery objectives, transaction performance, offline synchronization, concurrent users, data growth, retention and penetration-test thresholds require confirmation during detailed design."]]},
 {slug:"sop-manual",code:"D4",title:"Complete DFR SOP Manual",status:"Operational draft for validation",purpose:"Provides controlled step-by-step procedures, responsibilities, records, controls, exceptions and escalation for registry operations.",sections:[
  ["Manual structure","Nine controlled SOPs cover identification and registration; collection and validation; storage/protection/update; social-protection integration; grievance redress; monitoring/reporting; institutional coordination; consultation/validation; and change control."],
  ["Control model","Every procedure identifies trigger, authorized roles, prerequisites, numbered actions, validation rules, evidence, maker-checker decision, exceptions, escalation, service standard and audit requirement."],
  ["Institutional responsibilities","MoA is accountable for registry policy and operations; MGCSP for social-protection linkage; LISGIS for geography and statistical standards; local authorities for mobilization and local verification; FAO for assignment oversight and deliverable acceptance."],
  ["Approval","SOP owners propose changes; Data Governance and Operations review; affected institutions validate; MoA authorizes operational release; version, effective date and training completion are recorded."],
  ["Use","The interactive SOP Manual workspace contains the complete step sequence and RACI matrix. This document is the controlled narrative companion."],
  ["Validation required","Named positions, service-level times, legal citations, retention periods, escalation contacts and final committee mandates require stakeholder approval."]]},
 {slug:"functional-platform",code:"D5",title:"Functional and Interoperable Platform Report",status:"Platform operational—external connections pending",purpose:"Documents implemented functionality, configuration, integration readiness, security controls and outstanding dependencies.",sections:[
  ["Implemented","Farmer and household profiles, county/district registration, coordinates, GIS capture, duplicate screening, verification, programmes, payment accounts, vouchers, grievances, offline queue, RBAC workspaces, analytics, audit and FAO assignment controls."],
  ["Interoperability readiness","The catalogue records interface purpose, owner, mapping, method, security, test status and exchange history. Production connections depend on counterpart endpoints, credentials, agreements and test environments."],
  ["Security posture","Protected sign-in, scoped role presentation, encryption provided by the hosting environment, masked financial identifiers, controlled evidence storage and audited workflow events are implemented. Independent security testing remains an acceptance dependency."],
  ["Acceptance evidence","Requirements traceability, test results, defect closure, UAT decisions, performance evidence, security assessment, backup/restore test and operating procedures must accompany production acceptance."],
  ["Limitations","No claim is made that MTN, Orange, MGCSP, LISGIS or other external systems are live-connected until authorized credentials and successful end-to-end tests exist."]]},
 {slug:"training-report",code:"D6",title:"Training Materials and Training Report",status:"Curriculum draft—delivery records pending",purpose:"Defines role-based learning, practical assessment, attendance, certification and capacity-transfer reporting.",sections:[
  ["Learning tracks","National administrators; county/district officers; enumerators and supervisors; verification officers; programme/payment/voucher teams; GIS and analysts; help desk; security and audit; trainers and technical administrators."],
  ["Curriculum","Data protection and consent; farmer/household registration; offline synchronization; GIS parcels; validation and duplicates; service delivery; grievances; reports; access control; audit; support; incident and continuity procedures."],
  ["Delivery method","Facilitator demonstration, guided practice, scenario exercises, job aids, knowledge checks and supervised competency assessment using role-relevant tasks."],
  ["Certification","Attendance alone is insufficient. Certification requires the defined pass score, successful practical tasks and trainer confirmation. Remediation and reassessment are recorded."],
  ["Report fields","Session, location, institution, role, sex/age inclusion, attendance, pre/post score, practical result, certificate ID, feedback, issues and follow-up action."],
  ["Pending","Named participants, dates, actual attendance, assessment results, certificates and lessons will populate after approved training delivery."]]},
 {slug:"pilot-report",code:"D7",title:"Pilot-Implementation Report",status:"Pilot protocol ready—execution pending",purpose:"Controls pilot readiness, execution, evidence, results, defect resolution and the decision to scale.",sections:[
  ["Pilot scope","Representative counties and districts should test connectivity conditions, crop systems, institutional capacity, language/accessibility needs and integration scenarios. Final locations require approval."],
  ["Entry criteria","Approved SOPs, trained users, configured roles, migrated reference data, devices, connectivity plan, support desk, test completion, security approval, backup and rollback readiness."],
  ["Measures","Registration completeness, duplicate rate, verification turnaround, GPS quality, sync success, grievance response, service transactions, availability, user competency, farmer experience and inclusion."],
  ["Daily control","Issue triage, defect severity, workaround, accountable owner, target resolution, retest evidence, decision log and change approval."],
  ["Exit decision","Proceed, proceed with conditions, extend pilot, or stop. The decision requires evidence, unresolved-risk acceptance and signatures from designated authorities."],
  ["Pending results","Actual volumes, county results, user feedback, defects, performance and scale recommendation will be completed after pilot execution."]]},
 {slug:"final-report",code:"D8",title:"Final Report: Lessons Learned and Policy Recommendations",status:"Framework draft—completion dependent on implementation",purpose:"Consolidates delivery results, institutional learning, sustainability actions and policy recommendations.",sections:[
  ["Results framework","Report achievements against scope, milestones, acceptance decisions, coverage, quality, inclusion, service outcomes, institutional capacity and sustainability."],
  ["Learning method","Triangulate monitoring data, audit records, user/farmer feedback, workshops, incidents, defects, training evidence and institutional interviews."],
  ["Policy themes","Registry mandate and governance; consent and farmer rights; data-sharing; authoritative identifiers; inclusion; grievance and appeal; cybersecurity; retention; interoperability standards; sustainable financing and staffing."],
  ["Sustainability","Government ownership, operating budget, staffing, infrastructure lifecycle, source/configuration control, vendor independence, capacity transfer, support tiers, continuity tests and annual governance review."],
  ["Recommendation control","Each recommendation states evidence, responsible institution, urgency, dependency, resource implication, implementation date and monitoring indicator."],
  ["Pending completion","Final findings, measured outcomes, accepted lessons and policy decisions require evidence from the completed assignment and validated stakeholder consultation."]]}
] as const;
export function getDeliverable(slug:string){return deliverables.find(d=>d.slug===slug)}
