export interface FarmCadastre {
  id: string;
  maskedHolder: string;
  county: string;
  district: string;
  community: string;
  commodity: string;
  variety: string;
  areaHa: number;
  areaAcres: number;
  perimeterM: number;
  centroid: [number, number];
  accuracyM: number;
  roadAccess: string;
  roadCondition: string;
  roadDistanceMi: number;
  nearestMarket: string;
  marketDistanceKm: number;
  marketTravelMins: number;
  storageType: string;
  storageCapacityMt: number;
  processingFacility: string;
  processingDistanceMi: number;
  mechanizationMode: string;
  irrigationStatus: string;
  smartReadiness: string;
  verificationStatus: string;
  verifiedDate: string;
  vertices: [number, number][];
}

// Complete 15-County Georeferenced Cadastral Farm Holdings
export const SEEDED_PARCELS: FarmCadastre[] = [
  // 1. Bomi Parcels
  {
    id: "PCL-BM-00092",
    maskedHolder: "Farmer C. L. (Diversified Producer)",
    county: "Bomi",
    district: "Senjeh",
    community: "Tubmanburg Agro-Corridor",
    commodity: "Vegetables",
    variety: "Sweet Pepper, Bitterball, Okra",
    areaHa: 3.4,
    areaAcres: 8.4,
    perimeterM: 780,
    centroid: [6.694, -10.821],
    accuracyM: 1.2,
    roadAccess: "Paved Monrovia-Tubmanburg Highway",
    roadCondition: "Good",
    roadDistanceMi: 0.3,
    nearestMarket: "Tubmanburg Central Market",
    marketDistanceKm: 2.8,
    marketTravelMins: 12,
    storageType: "Ventilated packing shed & cool crates",
    storageCapacityMt: 3.5,
    processingFacility: "Bomi Farmers Cooperative Processing Facility",
    processingDistanceMi: 1.2,
    mechanizationMode: "Two-wheel rotary power tiller",
    irrigationStatus: "Solar pump drip irrigation",
    smartReadiness: "Weekly SMS commodity bulletin",
    verificationStatus: "FIELD_VERIFIED",
    verifiedDate: "2026-08-26",
    vertices: [
      [6.697, -10.825],
      [6.698, -10.816],
      [6.69, -10.815],
      [6.689, -10.826],
    ],
  },
  {
    id: "PCL-BM-00167",
    maskedHolder: "Farmer J. W. (Smallholder Lead)",
    county: "Bomi",
    district: "Klay",
    community: "Klay Agricultural Junction",
    commodity: "Cassava",
    variety: "TMS 96/026",
    areaHa: 4.6,
    areaAcres: 11.37,
    perimeterM: 910,
    centroid: [6.645, -10.865],
    accuracyM: 1.5,
    roadAccess: "Paved all-weather road",
    roadCondition: "Good",
    roadDistanceMi: 0.4,
    nearestMarket: "Klay Junction Market",
    marketDistanceKm: 1.5,
    marketTravelMins: 6,
    storageType: "Hermetic bulk storage & dried chips shed",
    storageCapacityMt: 5.0,
    processingFacility: "Klay Mechanized Gari Mill",
    processingDistanceMi: 0.9,
    mechanizationMode: "Tractor plowing service hire",
    irrigationStatus: "Rainfed with contour bunds",
    smartReadiness: "CBR-compliant digital farmer ID card",
    verificationStatus: "FIELD_VERIFIED",
    verifiedDate: "2026-08-07",
    vertices: [
      [6.648, -10.869],
      [6.649, -10.86],
      [6.641, -10.859],
      [6.64, -10.87],
    ],
  },

  // 2. Bong Parcels
  {
    id: "PCL-BG-00088",
    maskedHolder: "Farmer A. W. (Cooperative Lead)",
    county: "Bong",
    district: "Suakoko",
    community: "Kpatawee Rice Basin",
    commodity: "Rice",
    variety: "Suakoko 8 (Foundation seed)",
    areaHa: 6.2,
    areaAcres: 15.32,
    perimeterM: 1180,
    centroid: [7.012, -9.578],
    accuracyM: 1.1,
    roadAccess: "All-weather asphalt road",
    roadCondition: "Good",
    roadDistanceMi: 0.4,
    nearestMarket: "Gbarnga Central Market",
    marketDistanceKm: 9.8,
    marketTravelMins: 22,
    storageType: "Central cooperative grain bank (150 MT)",
    storageCapacityMt: 25.0,
    processingFacility: "Kpatawee Industrial Rice Complex",
    processingDistanceMi: 0.5,
    mechanizationMode: "4-wheel 50HP tractor + mechanical thresher",
    irrigationStatus: "Controlled gravity irrigation sluices",
    smartReadiness: "Soil sensor station & automated water gauges",
    verificationStatus: "FIELD_VERIFIED",
    verifiedDate: "2026-08-18",
    vertices: [
      [7.016, -9.583],
      [7.017, -9.573],
      [7.008, -9.572],
      [7.007, -9.584],
    ],
  },
  {
    id: "PCL-BG-00174",
    maskedHolder: "Farmer J. S. (Cassava Producer)",
    county: "Bong",
    district: "Jorquelleh",
    community: "Phebe Vicinity",
    commodity: "Cassava",
    variety: "CARICASS 2",
    areaHa: 3.2,
    areaAcres: 7.91,
    perimeterM: 760,
    centroid: [6.974, -9.612],
    accuracyM: 1.7,
    roadAccess: "Paved highway link",
    roadCondition: "Good",
    roadDistanceMi: 0.6,
    nearestMarket: "Phebe Junction Community Market",
    marketDistanceKm: 2.8,
    marketTravelMins: 10,
    storageType: "Ventilated fresh tuber storage",
    storageCapacityMt: 3.5,
    processingFacility: "CARI Agribusiness Incubation Hub",
    processingDistanceMi: 1.9,
    mechanizationMode: "Motorized cassava grater & hydraulic press",
    irrigationStatus: "Rainfed upland with contour bunds",
    smartReadiness: "SMS weather alerts & pest warning network",
    verificationStatus: "FIELD_VERIFIED",
    verifiedDate: "2026-07-19",
    vertices: [
      [6.977, -9.616],
      [6.978, -9.608],
      [6.97, -9.607],
      [6.969, -9.617],
    ],
  },

  // 3. Gbarpolu Parcels
  {
    id: "PCL-GP-00063",
    maskedHolder: "Farmer F. K. (Cooperative Member)",
    county: "Gbarpolu",
    district: "Bopolu",
    community: "Bopolu Forest Agroforestry Hub",
    commodity: "Cocoa",
    variety: "Organic Shade-Grown Cocoa",
    areaHa: 5.8,
    areaAcres: 14.33,
    perimeterM: 1080,
    centroid: [7.376, -10.287],
    accuracyM: 1.4,
    roadAccess: "Monrovia-Bopolu Highway",
    roadCondition: "Passable year-round",
    roadDistanceMi: 1.2,
    nearestMarket: "Bopolu Central Market",
    marketDistanceKm: 4.5,
    marketTravelMins: 18,
    storageType: "Raised solar drying beds & jute warehouse",
    storageCapacityMt: 6.0,
    processingFacility: "Gbarpolu Agribusiness Depot",
    processingDistanceMi: 2.2,
    mechanizationMode: "Motorized pruner & mist blower",
    irrigationStatus: "Rainfed tropical canopy forest",
    smartReadiness: "GPS cadastral boundary verified & QR tagged",
    verificationStatus: "FIELD_VERIFIED",
    verifiedDate: "2026-08-17",
    vertices: [
      [7.38, -10.292],
      [7.381, -10.282],
      [7.371, -10.281],
      [7.37, -10.293],
    ],
  },
  {
    id: "PCL-GP-00148",
    maskedHolder: "Farmer R. V. (Smallholder)",
    county: "Gbarpolu",
    district: "Belleh",
    community: "Belleh Yella Basin",
    commodity: "Rice",
    variety: "NERICA L-19 (Lowland)",
    areaHa: 4.0,
    areaAcres: 9.88,
    perimeterM: 880,
    centroid: [7.41, -10.245],
    accuracyM: 1.6,
    roadAccess: "Graded laterite county road",
    roadCondition: "Fair",
    roadDistanceMi: 1.8,
    nearestMarket: "Bopolu Market",
    marketDistanceKm: 12.4,
    marketTravelMins: 45,
    storageType: "Community grain store",
    storageCapacityMt: 4.5,
    processingFacility: "Belleh Rice Processing Station",
    processingDistanceMi: 3.1,
    mechanizationMode: "Manual + power tiller service hire",
    irrigationStatus: "Inland valley swamp (IVS)",
    smartReadiness: "SMS price information",
    verificationStatus: "FIELD_VERIFIED",
    verifiedDate: "2026-08-01",
    vertices: [
      [7.414, -10.249],
      [7.415, -10.24],
      [7.406, -10.239],
      [7.405, -10.25],
    ],
  },

  // 4. Grand Bassa Parcels
  {
    id: "PCL-GB-00076",
    maskedHolder: "Farmer T. V. (Cassava Nucleus)",
    county: "Grand Bassa",
    district: "Owensgrove",
    community: "St. John River Bank",
    commodity: "Cassava",
    variety: "TME 419 (Disease-resistant)",
    areaHa: 4.5,
    areaAcres: 11.12,
    perimeterM: 920,
    centroid: [5.924, -10.024],
    accuracyM: 1.4,
    roadAccess: "All-weather coastal highway link",
    roadCondition: "Good",
    roadDistanceMi: 0.7,
    nearestMarket: "Buchanan Port Commercial Market",
    marketDistanceKm: 16.5,
    marketTravelMins: 35,
    storageType: "Ventilated bulk holding cribs",
    storageCapacityMt: 8.0,
    processingFacility: "Grand Bassa Gari & Starch Enterprise",
    processingDistanceMi: 1.5,
    mechanizationMode: "Tractor plowing + mechanized dewatering press",
    irrigationStatus: "Rainfed with natural riverbank sub-irrigation",
    smartReadiness: "USSD registry status verification",
    verificationStatus: "FIELD_VERIFIED",
    verifiedDate: "2026-07-22",
    vertices: [
      [5.928, -10.029],
      [5.929, -10.019],
      [5.92, -10.018],
      [5.919, -10.03],
    ],
  },
  {
    id: "PCL-GB-00142",
    maskedHolder: "Farmer E. S. (Oil Palm Outgrower)",
    county: "Grand Bassa",
    district: "Buchanan",
    community: "Fairground Agro Hub",
    commodity: "Oil Palm",
    variety: "Tenera Hybrid Seedlings",
    areaHa: 5.2,
    areaAcres: 12.85,
    perimeterM: 1040,
    centroid: [5.882, -9.985],
    accuracyM: 1.3,
    roadAccess: "Paved port road",
    roadCondition: "Excellent",
    roadDistanceMi: 0.3,
    nearestMarket: "Buchanan Central Market",
    marketDistanceKm: 3.2,
    marketTravelMins: 10,
    storageType: "Fresh fruit bunch collection ramp",
    storageCapacityMt: 12.0,
    processingFacility: "Buchanan Agro-Processing Complex",
    processingDistanceMi: 1.8,
    mechanizationMode: "Tractor haulage trailer + mechanized digester",
    irrigationStatus: "Rainfed high-rainfall coastal belt",
    smartReadiness: "Traceability QR code tagged & GPS validated",
    verificationStatus: "FIELD_VERIFIED",
    verifiedDate: "2026-08-12",
    vertices: [
      [5.886, -9.99],
      [5.887, -9.98],
      [5.878, -9.979],
      [5.877, -9.991],
    ],
  },

  // 5. Grand Cape Mount Parcels
  {
    id: "PCL-CM-00084",
    maskedHolder: "Farmer B. Z. (Women's Ag Group)",
    county: "Grand Cape Mount",
    district: "Tewor",
    community: "Bo Waterside Trade Corridor",
    commodity: "Cassava",
    variety: "TME 419 (High dry-matter)",
    areaHa: 4.1,
    areaAcres: 10.13,
    perimeterM: 860,
    centroid: [7.022, -11.108],
    accuracyM: 1.3,
    roadAccess: "Paved International Corridor",
    roadCondition: "Good",
    roadDistanceMi: 0.2,
    nearestMarket: "Bo Waterside International Border Market",
    marketDistanceKm: 2.5,
    marketTravelMins: 8,
    storageType: "Hermetic bulk storage & dried chips shed",
    storageCapacityMt: 6.5,
    processingFacility: "Tewor Gari & Starch Enterprise",
    processingDistanceMi: 1.4,
    mechanizationMode: "Tractor service hire + hydraulic press",
    irrigationStatus: "Rainfed with coastal humidity",
    smartReadiness: "Cross-border digital farmer trade pass",
    verificationStatus: "FIELD_VERIFIED",
    verifiedDate: "2026-08-23",
    vertices: [
      [7.026, -11.113],
      [7.027, -11.103],
      [7.017, -11.102],
      [7.016, -11.114],
    ],
  },
  {
    id: "PCL-CM-00155",
    maskedHolder: "Farmer V. M. (Outgrower)",
    county: "Grand Cape Mount",
    district: "Porkpa",
    community: "Dambala Agriculture Zone",
    commodity: "Rice",
    variety: "NERICA Lowland L-19",
    areaHa: 5.5,
    areaAcres: 13.59,
    perimeterM: 1060,
    centroid: [7.065, -11.15],
    accuracyM: 1.5,
    roadAccess: "All-weather gravel road",
    roadCondition: "Good",
    roadDistanceMi: 0.9,
    nearestMarket: "Sinje Junction Market",
    marketDistanceKm: 8.4,
    marketTravelMins: 25,
    storageType: "Community grain bank",
    storageCapacityMt: 8.0,
    processingFacility: "Porkpa Modern Rice Mill",
    processingDistanceMi: 2.3,
    mechanizationMode: "Power tiller & motorized thresher",
    irrigationStatus: "Perennial stream diversion",
    smartReadiness: "Mobile money registration",
    verificationStatus: "FIELD_VERIFIED",
    verifiedDate: "2026-07-29",
    vertices: [
      [7.069, -11.155],
      [7.07, -11.145],
      [7.06, -11.144],
      [7.059, -11.156],
    ],
  },

  // 6. Grand Gedeh Parcels
  {
    id: "PCL-GG-00045",
    maskedHolder: "Farmer G. P. (Agroforestry Lead)",
    county: "Grand Gedeh",
    district: "Tchien",
    community: "Zwedru East Agroforestry",
    commodity: "Cocoa",
    variety: "Criollo & Forastero F1 Hybrid",
    areaHa: 6.4,
    areaAcres: 15.81,
    perimeterM: 1140,
    centroid: [6.008, -8.229],
    accuracyM: 1.2,
    roadAccess: "All-weather Ganta-Zwedru corridor",
    roadCondition: "Good",
    roadDistanceMi: 0.5,
    nearestMarket: "Zwedru Central Commercial Market",
    marketDistanceKm: 4.2,
    marketTravelMins: 15,
    storageType: "Solar drying shed & moisture-controlled depot",
    storageCapacityMt: 10.0,
    processingFacility: "Grand Gedeh Cocoa Quality Hub",
    processingDistanceMi: 1.6,
    mechanizationMode: "Mechanical pod breaker & motorized mist blower",
    irrigationStatus: "Rainfed agroforestry canopy",
    smartReadiness: "EUDR deforestation-free polygon verified",
    verificationStatus: "FIELD_VERIFIED",
    verifiedDate: "2026-08-19",
    vertices: [
      [6.012, -8.234],
      [6.013, -8.224],
      [6.003, -8.223],
      [6.002, -8.235],
    ],
  },
  {
    id: "PCL-GG-00162",
    maskedHolder: "Farmer M. T. (Cassava Producer)",
    county: "Grand Gedeh",
    district: "Konobo",
    community: "Konobo Farmlands",
    commodity: "Cassava",
    variety: "CARICASS 1",
    areaHa: 3.8,
    areaAcres: 9.39,
    perimeterM: 820,
    centroid: [5.962, -8.185],
    accuracyM: 1.5,
    roadAccess: "Feeder road link",
    roadCondition: "Fair",
    roadDistanceMi: 1.4,
    nearestMarket: "Zwedru Market",
    marketDistanceKm: 14.6,
    marketTravelMins: 45,
    storageType: "Hermetic bags & tuber shed",
    storageCapacityMt: 5.5,
    processingFacility: "Konobo Gari Processing Center",
    processingDistanceMi: 2.0,
    mechanizationMode: "Mechanized grater & press",
    irrigationStatus: "Rainfed",
    smartReadiness: "SMS weather alerts",
    verificationStatus: "FIELD_VERIFIED",
    verifiedDate: "2026-07-30",
    vertices: [
      [5.965, -8.189],
      [5.966, -8.18],
      [5.958, -8.179],
      [5.957, -8.19],
    ],
  },

  // 7. Grand Kru Parcels
  {
    id: "PCL-GK-00057",
    maskedHolder: "Farmer W. T. (Smallholder Lead)",
    county: "Grand Kru",
    district: "Barclayville",
    community: "Barclayville Agricultural Basin",
    commodity: "Cassava",
    variety: "TMS 96/026 (High starch)",
    areaHa: 3.6,
    areaAcres: 8.9,
    perimeterM: 790,
    centroid: [4.792, -8.151],
    accuracyM: 1.4,
    roadAccess: "Coastal unpaved highway",
    roadCondition: "Fair",
    roadDistanceMi: 0.8,
    nearestMarket: "Barclayville Central Market",
    marketDistanceKm: 2.2,
    marketTravelMins: 10,
    storageType: "Ventilated fresh tuber store",
    storageCapacityMt: 4.0,
    processingFacility: "Grand Kru Gari Processing Hub",
    processingDistanceMi: 1.1,
    mechanizationMode: "Motorized cassava grater",
    irrigationStatus: "Rainfed coastal high rainfall",
    smartReadiness: "Mobile money agro-wallet",
    verificationStatus: "FIELD_VERIFIED",
    verifiedDate: "2026-08-08",
    vertices: [
      [4.795, -8.155],
      [4.796, -8.146],
      [4.788, -8.145],
      [4.787, -8.156],
    ],
  },
  {
    id: "PCL-GK-00133",
    maskedHolder: "Farmer J. N. (Outgrower)",
    county: "Grand Kru",
    district: "Sasstown",
    community: "Sasstown Farmlands",
    commodity: "Oil Palm",
    variety: "Tenera Hybrid",
    areaHa: 4.8,
    areaAcres: 11.86,
    perimeterM: 990,
    centroid: [4.825, -8.21],
    accuracyM: 1.6,
    roadAccess: "Feeder road",
    roadCondition: "Seasonal",
    roadDistanceMi: 1.2,
    nearestMarket: "Sasstown Commercial Wharf",
    marketDistanceKm: 5.4,
    marketTravelMins: 20,
    storageType: "FFB collection depot",
    storageCapacityMt: 8.0,
    processingFacility: "Sasstown Palm Oil Press",
    processingDistanceMi: 1.7,
    mechanizationMode: "Hand-powered press & thresher",
    irrigationStatus: "Rainfed",
    smartReadiness: "SMS advisory network",
    verificationStatus: "FIELD_VERIFIED",
    verifiedDate: "2026-07-25",
    vertices: [
      [4.828, -8.214],
      [4.829, -8.205],
      [4.821, -8.204],
      [4.82, -8.215],
    ],
  },

  // 8. Lofa Parcels
  {
    id: "PCL-LF-00033",
    maskedHolder: "Farmer K. B. (Commercial Grain)",
    county: "Lofa",
    district: "Foya",
    community: "Foya City Farmlands",
    commodity: "Rice",
    variety: "Foya Special (Fragrant Jasmine)",
    areaHa: 8.5,
    areaAcres: 21.0,
    perimeterM: 1420,
    centroid: [8.358, -10.218],
    accuracyM: 1.3,
    roadAccess: "Engineered gravel highway",
    roadCondition: "Good",
    roadDistanceMi: 0.8,
    nearestMarket: "Foya Cross-Border Commercial Market",
    marketDistanceKm: 5.2,
    marketTravelMins: 18,
    storageType: "Metal grain silos & palletized warehouse",
    storageCapacityMt: 35.0,
    processingFacility: "Foya Rural Women Cooperative Mill",
    processingDistanceMi: 1.1,
    mechanizationMode: "Tractor disc plow & combine harvester hire",
    irrigationStatus: "Inland valley swamp (IVS) developed scheme",
    smartReadiness: "CBR-compliant digital farmer ID card & NFC",
    verificationStatus: "FIELD_VERIFIED",
    verifiedDate: "2026-08-25",
    vertices: [
      [8.363, -10.224],
      [8.365, -10.212],
      [8.352, -10.211],
      [8.351, -10.225],
    ],
  },
  {
    id: "PCL-LF-00129",
    maskedHolder: "Farmer M. D. (Cocoa Farmer)",
    county: "Lofa",
    district: "Voinjama",
    community: "Boluwongai",
    commodity: "Cocoa",
    variety: "Organic Fairtrade Cocoa",
    areaHa: 4.8,
    areaAcres: 11.86,
    perimeterM: 980,
    centroid: [8.412, -9.754],
    accuracyM: 1.5,
    roadAccess: "Unpaved feeder road",
    roadCondition: "Seasonal (Passable dry/light rain)",
    roadDistanceMi: 1.9,
    nearestMarket: "Voinjama Central Market",
    marketDistanceKm: 14.2,
    marketTravelMins: 45,
    storageType: "Solar dryer & moisture-proof bagging",
    storageCapacityMt: 7.5,
    processingFacility: "Voinjama Organic Cocoa Hub",
    processingDistanceMi: 2.8,
    mechanizationMode: "Manual weeding + mechanical pod breakers",
    irrigationStatus: "Rainfed canopy forest",
    smartReadiness: "Mobile money receipt for harvest sales",
    verificationStatus: "FIELD_VERIFIED",
    verifiedDate: "2026-08-11",
    vertices: [
      [8.416, -9.759],
      [8.417, -9.749],
      [8.407, -9.748],
      [8.406, -9.76],
    ],
  },

  // 9. Margibi Parcels
  {
    id: "PCL-MG-00052",
    maskedHolder: "Farmer P. C. (Vegetable Outgrower)",
    county: "Margibi",
    district: "Kakata",
    community: "Weala Corridor",
    commodity: "Vegetables",
    variety: "Cabbage, Tomatoes, Cucumber",
    areaHa: 2.4,
    areaAcres: 5.93,
    perimeterM: 640,
    centroid: [6.538, -10.294],
    accuracyM: 1.5,
    roadAccess: "Paved Kakata highway",
    roadCondition: "Excellent",
    roadDistanceMi: 0.3,
    nearestMarket: "Kakata Central Commercial Market",
    marketDistanceKm: 4.8,
    marketTravelMins: 14,
    storageType: "Cold-pack insulated vegetable crates",
    storageCapacityMt: 3.0,
    processingFacility: "Kakata Horti-Aggregation Center",
    processingDistanceMi: 1.0,
    mechanizationMode: "Two-wheel walk-behind cultivator",
    irrigationStatus: "Borehole pump + overhead sprinklers",
    smartReadiness: "Weekly SMS commodity price dashboard",
    verificationStatus: "FIELD_VERIFIED",
    verifiedDate: "2026-08-02",
    vertices: [
      [6.541, -10.297],
      [6.542, -10.29],
      [6.534, -10.289],
      [6.533, -10.298],
    ],
  },
  {
    id: "PCL-MG-00188",
    maskedHolder: "Farmer K. R. (Cassava & Rubber)",
    county: "Margibi",
    district: "Gibi",
    community: "Peter's Town",
    commodity: "Cassava",
    variety: "TMS 96/026",
    areaHa: 4.6,
    areaAcres: 11.37,
    perimeterM: 920,
    centroid: [6.502, -10.221],
    accuracyM: 1.4,
    roadAccess: "All-weather laterite road",
    roadCondition: "Good",
    roadDistanceMi: 0.5,
    nearestMarket: "Kakata Market",
    marketDistanceKm: 8.6,
    marketTravelMins: 22,
    storageType: "Ventilated bulk holding cribs",
    storageCapacityMt: 6.0,
    processingFacility: "Gibi Agribusiness Mill",
    processingDistanceMi: 1.5,
    mechanizationMode: "Tractor hire service",
    irrigationStatus: "Rainfed",
    smartReadiness: "SMS market price alerts",
    verificationStatus: "FIELD_VERIFIED",
    verifiedDate: "2026-07-28",
    vertices: [
      [6.505, -10.225],
      [6.506, -10.216],
      [6.498, -10.215],
      [6.497, -10.226],
    ],
  },

  // 10. Maryland Parcels
  {
    id: "PCL-MY-00019",
    maskedHolder: "Farmer O. L. (Oil Palm Smallholder)",
    county: "Maryland",
    district: "Pleebo-Sodoken",
    community: "Pleebo Outskirts",
    commodity: "Oil Palm",
    variety: "Tenera Hybrid Seedlings",
    areaHa: 6.8,
    areaAcres: 16.8,
    perimeterM: 1250,
    centroid: [4.584, -7.694],
    accuracyM: 1.3,
    roadAccess: "Paved Harper-Pleebo highway",
    roadCondition: "Good",
    roadDistanceMi: 0.4,
    nearestMarket: "Pleebo Commercial Market",
    marketDistanceKm: 3.2,
    marketTravelMins: 10,
    storageType: "Fresh fruit bunch (FFB) collection ramp",
    storageCapacityMt: 18.0,
    processingFacility: "Pleebo Industrial Palm Oil Mill",
    processingDistanceMi: 2.1,
    mechanizationMode: "Tractor haulage trailer + mechanized digester",
    irrigationStatus: "Rainfed high-precipitation coastal zone",
    smartReadiness: "QR-tagged traceability for RSPO certification",
    verificationStatus: "FIELD_VERIFIED",
    verifiedDate: "2026-08-16",
    vertices: [
      [4.589, -7.7],
      [4.59, -7.688],
      [4.579, -7.687],
      [4.578, -7.701],
    ],
  },
  {
    id: "PCL-MY-00084",
    maskedHolder: "Farmer H. S. (Rice Producer)",
    county: "Maryland",
    district: "Harper",
    community: "Hoffman Station",
    commodity: "Rice",
    variety: "Nerica L-19",
    areaHa: 3.9,
    areaAcres: 9.64,
    perimeterM: 810,
    centroid: [4.425, -7.74],
    accuracyM: 1.4,
    roadAccess: "Paved port access road",
    roadCondition: "Good",
    roadDistanceMi: 0.3,
    nearestMarket: "Harper Commercial Port Market",
    marketDistanceKm: 2.1,
    marketTravelMins: 8,
    storageType: "PICS hermetic bags",
    storageCapacityMt: 6.0,
    processingFacility: "Harper Cooperative Grain Hub",
    processingDistanceMi: 1.0,
    mechanizationMode: "Power tiller & mechanical thresher",
    irrigationStatus: "Coastal swamp irrigation sluice",
    smartReadiness: "Mobile money payout linked",
    verificationStatus: "FIELD_VERIFIED",
    verifiedDate: "2026-08-03",
    vertices: [
      [4.428, -7.744],
      [4.429, -7.735],
      [4.421, -7.734],
      [4.42, -7.745],
    ],
  },

  // 11. Montserrado Parcels
  {
    id: "PCL-MO-00412",
    maskedHolder: "Farmer H. K. (Smallholder)",
    county: "Montserrado",
    district: "Todee",
    community: "Nyenhn",
    commodity: "Vegetables",
    variety: "Sweet Pepper, Bitterball, Okra",
    areaHa: 2.8,
    areaAcres: 6.92,
    perimeterM: 710,
    centroid: [6.612, -10.584],
    accuracyM: 1.4,
    roadAccess: "Paved all-weather road",
    roadCondition: "Good",
    roadDistanceMi: 0.3,
    nearestMarket: "Red Light Wholesale Market, Paynesville",
    marketDistanceKm: 18.2,
    marketTravelMins: 40,
    storageType: "Community ventilated warehouse & crates",
    storageCapacityMt: 4.5,
    processingFacility: "Todee Agro Aggregation Center",
    processingDistanceMi: 0.8,
    mechanizationMode: "Semi-mechanized (Rotary power tiller)",
    irrigationStatus: "Solar drip irrigation & shallow well",
    smartReadiness: "USSD market prices & daily rainfall SMS",
    verificationStatus: "FIELD_VERIFIED",
    verifiedDate: "2026-08-14",
    vertices: [
      [6.614, -10.587],
      [6.615, -10.582],
      [6.61, -10.581],
      [6.609, -10.586],
    ],
  },
  {
    id: "PCL-MO-00489",
    maskedHolder: "Farmer D. T. (Coop Member)",
    county: "Montserrado",
    district: "Careysburg",
    community: "Bensonville Outskirts",
    commodity: "Cassava",
    variety: "TMS 96/026 (High starch)",
    areaHa: 3.5,
    areaAcres: 8.65,
    perimeterM: 840,
    centroid: [6.495, -10.612],
    accuracyM: 1.8,
    roadAccess: "Paved all-weather road",
    roadCondition: "Fair",
    roadDistanceMi: 0.5,
    nearestMarket: "Careysburg Junction Market",
    marketDistanceKm: 4.1,
    marketTravelMins: 15,
    storageType: "Hermetic bulk storage & dried chips shed",
    storageCapacityMt: 6.0,
    processingFacility: "Bensonville Mechanized Gari Mill",
    processingDistanceMi: 1.2,
    mechanizationMode: "Tractor plowing service hire",
    irrigationStatus: "Rainfed with drainage canals",
    smartReadiness: "Basic mobile feature phone (SMS alerts)",
    verificationStatus: "FIELD_VERIFIED",
    verifiedDate: "2026-07-28",
    vertices: [
      [6.498, -10.615],
      [6.499, -10.608],
      [6.492, -10.609],
      [6.491, -10.616],
    ],
  },

  // 12. Nimba Parcels
  {
    id: "PCL-NI-00104",
    maskedHolder: "Farmer B. M. (Master Cocoa Producer)",
    county: "Nimba",
    district: "Sanniquellie-Mahn",
    community: "Lugbehyee",
    commodity: "Cocoa",
    variety: "Criollo & Forastero F1 Hybrid",
    areaHa: 5.4,
    areaAcres: 13.34,
    perimeterM: 1050,
    centroid: [7.362, -8.718],
    accuracyM: 1.2,
    roadAccess: "Graded laterite feeder road",
    roadCondition: "Passable year-round",
    roadDistanceMi: 1.1,
    nearestMarket: "Ganta International Border Market",
    marketDistanceKm: 26.5,
    marketTravelMins: 50,
    storageType: "Raised solar drying beds & jute warehouse",
    storageCapacityMt: 12.0,
    processingFacility: "Nimba Cocoa Fermentary & Quality Hub",
    processingDistanceMi: 2.4,
    mechanizationMode: "Motorized mist blower & mechanical pruners",
    irrigationStatus: "Rainfed upland canopy agroforestry",
    smartReadiness: "Traceability QR code tagged & GPS validated",
    verificationStatus: "FIELD_VERIFIED",
    verifiedDate: "2026-08-20",
    vertices: [
      [7.366, -8.722],
      [7.367, -8.714],
      [7.358, -8.713],
      [7.357, -8.723],
    ],
  },
  {
    id: "PCL-NI-00215",
    maskedHolder: "Farmer E. G. (Outgrower)",
    county: "Nimba",
    district: "Garr Bain",
    community: "Ganta Rural",
    commodity: "Rice",
    variety: "Nerica L-19 (Lowland swamp)",
    areaHa: 4.1,
    areaAcres: 10.13,
    perimeterM: 890,
    centroid: [7.288, -8.965],
    accuracyM: 1.6,
    roadAccess: "Paved Monrovia-Ganta Highway",
    roadCondition: "Excellent",
    roadDistanceMi: 0.2,
    nearestMarket: "Ganta Central Market",
    marketDistanceKm: 3.5,
    marketTravelMins: 12,
    storageType: "PICS bags & metal storage silo",
    storageCapacityMt: 8.5,
    processingFacility: "Ganta Modern Rice Dehuller & Polisher",
    processingDistanceMi: 1.8,
    mechanizationMode: "Walk-behind power tiller & drum seeder",
    irrigationStatus: "Perennial stream diversion canal",
    smartReadiness: "Smartphone DFR PWA & mobile money integration",
    verificationStatus: "FIELD_VERIFIED",
    verifiedDate: "2026-08-05",
    vertices: [
      [7.291, -8.969],
      [7.292, -8.961],
      [7.285, -8.96],
      [7.284, -8.97],
    ],
  },

  // 13. River Cess Parcels
  {
    id: "PCL-RC-00041",
    maskedHolder: "Farmer M. J. (Riverine Lead)",
    county: "River Cess",
    district: "Cestos City",
    community: "Cestos River Agricultural Basin",
    commodity: "Rice",
    variety: "Nerica L-19 (Swamp)",
    areaHa: 4.4,
    areaAcres: 10.87,
    perimeterM: 930,
    centroid: [5.912, -9.431],
    accuracyM: 1.3,
    roadAccess: "Buchanan-Cestos coastal link",
    roadCondition: "Good",
    roadDistanceMi: 0.6,
    nearestMarket: "Cestos Commercial Wharf Market",
    marketDistanceKm: 3.5,
    marketTravelMins: 12,
    storageType: "PICS hermetic storage bags",
    storageCapacityMt: 7.0,
    processingFacility: "River Cess Rice Dehuller & Polisher",
    processingDistanceMi: 1.4,
    mechanizationMode: "Walk-behind rotary power tiller",
    irrigationStatus: "Controlled river inundation gates",
    smartReadiness: "DFR Registry QR verification card",
    verificationStatus: "FIELD_VERIFIED",
    verifiedDate: "2026-08-21",
    vertices: [
      [5.916, -9.436],
      [5.917, -9.426],
      [5.907, -9.425],
      [5.906, -9.437],
    ],
  },
  {
    id: "PCL-RC-00122",
    maskedHolder: "Farmer H. D. (Smallholder)",
    county: "River Cess",
    district: "Morweh",
    community: "Boegeezay Community",
    commodity: "Cassava",
    variety: "CARICASS 2",
    areaHa: 3.5,
    areaAcres: 8.65,
    perimeterM: 780,
    centroid: [5.945, -9.472],
    accuracyM: 1.5,
    roadAccess: "Graded laterite road",
    roadCondition: "Fair",
    roadDistanceMi: 1.5,
    nearestMarket: "Cestos City Market",
    marketDistanceKm: 18.2,
    marketTravelMins: 50,
    storageType: "Ventilated bulk tuber shed",
    storageCapacityMt: 4.5,
    processingFacility: "Morweh Agro Aggregation Hub",
    processingDistanceMi: 2.1,
    mechanizationMode: "Mechanical grinder & press",
    irrigationStatus: "Rainfed",
    smartReadiness: "USSD weather service",
    verificationStatus: "FIELD_VERIFIED",
    verifiedDate: "2026-08-04",
    vertices: [
      [5.948, -9.476],
      [5.949, -9.467],
      [5.941, -9.466],
      [5.94, -9.477],
    ],
  },

  // 14. River Gee Parcels
  {
    id: "PCL-RG-00028",
    maskedHolder: "Farmer N. Y. (Master Farmer)",
    county: "River Gee",
    district: "Potupo",
    community: "Fish Town Agricultural Perimeter",
    commodity: "Rice",
    variety: "Suakoko 8 (Foundation seed)",
    areaHa: 5.1,
    areaAcres: 12.6,
    perimeterM: 1020,
    centroid: [5.196, -7.742],
    accuracyM: 1.2,
    roadAccess: "Harper-Fish Town Highway",
    roadCondition: "Good",
    roadDistanceMi: 0.5,
    nearestMarket: "Fish Town Central Market",
    marketDistanceKm: 3.8,
    marketTravelMins: 12,
    storageType: "Central grain bank (15 MT)",
    storageCapacityMt: 15.0,
    processingFacility: "River Gee Grain & Seed Hub",
    processingDistanceMi: 1.2,
    mechanizationMode: "Tractor plowing service hire",
    irrigationStatus: "Stream diversion canal",
    smartReadiness: "NFC digital farmer ID card",
    verificationStatus: "FIELD_VERIFIED",
    verifiedDate: "2026-08-27",
    vertices: [
      [5.2, -7.747],
      [5.201, -7.737],
      [5.191, -7.736],
      [5.19, -7.748],
    ],
  },
  {
    id: "PCL-RG-00115",
    maskedHolder: "Farmer D. Q. (Cooperative Member)",
    county: "River Gee",
    district: "Webbo",
    community: "Dweken Outskirts",
    commodity: "Cocoa",
    variety: "Organic Fairtrade F1",
    areaHa: 4.3,
    areaAcres: 10.63,
    perimeterM: 910,
    centroid: [5.234, -7.785],
    accuracyM: 1.5,
    roadAccess: "Graded laterite road",
    roadCondition: "Fair",
    roadDistanceMi: 1.1,
    nearestMarket: "Fish Town Market",
    marketDistanceKm: 11.5,
    marketTravelMins: 35,
    storageType: "Solar drying platform",
    storageCapacityMt: 6.0,
    processingFacility: "Webbo Agro Depot",
    processingDistanceMi: 2.4,
    mechanizationMode: "Motorized pruner",
    irrigationStatus: "Rainfed",
    smartReadiness: "USSD market prices",
    verificationStatus: "FIELD_VERIFIED",
    verifiedDate: "2026-08-10",
    vertices: [
      [5.237, -7.789],
      [5.238, -7.78],
      [5.23, -7.779],
      [5.229, -7.79],
    ],
  },

  // 15. Sinoe Parcels (Selected by user!)
  {
    id: "PCL-SI-00108",
    maskedHolder: "Farmer S. W. (Oil Palm Producer)",
    county: "Sinoe",
    district: "Butaw",
    community: "Butaw Oil Palm Outgrower Basin",
    commodity: "Oil Palm",
    variety: "Tenera High-Yield",
    areaHa: 5.6,
    areaAcres: 13.84,
    perimeterM: 1090,
    centroid: [5.372, -8.788],
    accuracyM: 1.3,
    roadAccess: "All-weather Coastal Highway",
    roadCondition: "Good",
    roadDistanceMi: 0.4,
    nearestMarket: "Greenville Commercial Port & Market",
    marketDistanceKm: 7.5,
    marketTravelMins: 20,
    storageType: "Bulk oil storage & FFB collection ramp",
    storageCapacityMt: 16.0,
    processingFacility: "Sinoe Palm Oil Mill & Refinery",
    processingDistanceMi: 2.5,
    mechanizationMode: "Tractor haulage & mechanized bunch thresher",
    irrigationStatus: "Rainfed high-rainfall coastal regime",
    smartReadiness: "RSPO smallholder traceability QR tag",
    verificationStatus: "FIELD_VERIFIED",
    verifiedDate: "2026-08-22",
    vertices: [
      [5.375, -8.792],
      [5.376, -8.783],
      [5.368, -8.782],
      [5.367, -8.793],
    ],
  },
  {
    id: "PCL-SI-00219",
    maskedHolder: "Farmer E. K. (Coop Secretary)",
    county: "Sinoe",
    district: "Juarzon",
    community: "Kpanyan Lowlands",
    commodity: "Rice",
    variety: "NERICA Lowland Swamp",
    areaHa: 4.2,
    areaAcres: 10.38,
    perimeterM: 890,
    centroid: [5.415, -8.825],
    accuracyM: 1.5,
    roadAccess: "Graded laterite county road",
    roadCondition: "Good",
    roadDistanceMi: 1.0,
    nearestMarket: "Greenville Central Market",
    marketDistanceKm: 12.8,
    marketTravelMins: 35,
    storageType: "Community grain bank & hermetic storage",
    storageCapacityMt: 8.5,
    processingFacility: "Juarzon Community Rice Dehuller",
    processingDistanceMi: 1.8,
    mechanizationMode: "Power tiller & pedal thresher",
    irrigationStatus: "Swamp drainage & water control gates",
    smartReadiness: "USSD mobile money payment registered",
    verificationStatus: "FIELD_VERIFIED",
    verifiedDate: "2026-08-15",
    vertices: [
      [5.418, -8.829],
      [5.419, -8.82],
      [5.411, -8.819],
      [5.41, -8.83],
    ],
  },
];
