import {desc,eq,sql} from "drizzle-orm";
import {NextRequest,NextResponse} from "next/server";
import {getDb} from "../../../db";
import {auditEvents,farmParcels} from "../../../db/schema";
import {realtimeBus} from "../../../lib/realtime-bus";
export const dynamic="force-dynamic";

export async function GET(){const db=await getDb();const rows=await db.select().from(farmParcels).orderBy(desc(farmParcels.updatedAt));return NextResponse.json(rows.map(r=>({...r,vertices:JSON.parse(r.vertices),qualityFlags:JSON.parse(r.qualityFlags)})))}
export async function POST(req:NextRequest){const b=await req.json();if(!Array.isArray(b.vertices)||b.vertices.length<3)return NextResponse.json({error:"A valid parcel requires at least three vertices."},{status:400});const db=await getDb();const parcelId=b.parcelId||`LBR-PCL-${Date.now().toString().slice(-8)}`;await db.insert(farmParcels).values({parcelId,farmerDfrId:b.farmerDfrId||"",farmerName:b.farmerName||"Unassigned parcel",county:b.county||"Unassigned",district:b.district||"",commodity:b.commodity||"",vertices:JSON.stringify(b.vertices),areaHectares:+b.areaHectares,areaAcres:+b.areaAcres,perimeterMeters:+b.perimeterMeters,centroidLat:+b.centroidLat,centroidLng:+b.centroidLng,gpsAccuracy:+b.gpsAccuracy||0,geometryStatus:b.geometryStatus||"UNVERIFIED",qualityFlags:JSON.stringify(b.qualityFlags||[])});await db.insert(auditEvents).values({actor:"GIS Officer",action:"Parcel boundary created",entity:parcelId,details:`${b.areaHectares} ha · ${b.vertices.length} vertices`});realtimeBus.publish("parcel:created",{parcelId,areaHectares:+b.areaHectares,farmerName:b.farmerName,county:b.county});return NextResponse.json({ok:true,parcelId},{status:201})}
export async function PATCH(req:NextRequest){const b=await req.json();const db=await getDb();const row=(await db.select().from(farmParcels).where(eq(farmParcels.parcelId,b.parcelId)).limit(1))[0];if(!row)return NextResponse.json({error:"Parcel not found"},{status:404});const values:any={updatedAt:sql`CURRENT_TIMESTAMP`};if(b.vertices){values.vertices=JSON.stringify(b.vertices);values.areaHectares=+b.areaHectares;values.areaAcres=+b.areaAcres;values.perimeterMeters=+b.perimeterMeters;values.centroidLat=+b.centroidLat;values.centroidLng=+b.centroidLng;values.qualityFlags=JSON.stringify(b.qualityFlags||[]);values.geometryStatus="UNVERIFIED";values.revision=row.revision+1}if(b.geometryStatus){values.geometryStatus=b.geometryStatus;values.verifiedBy=b.verifiedBy||"Authorized GIS Officer";values.verifiedAt=new Date().toISOString()}await db.update(farmParcels).set(values).where(eq(farmParcels.parcelId,b.parcelId));await db.insert(auditEvents).values({actor:"GIS Officer",action:b.geometryStatus==="FIELD_VERIFIED"?"Parcel field verified":"Parcel boundary revised",entity:b.parcelId,details:`Revision ${values.revision||row.revision}`});realtimeBus.publish("parcel:verified",{parcelId:b.parcelId,geometryStatus:b.geometryStatus});return NextResponse.json({ok:true})}
