"use client";
import {FormEvent,useEffect,useState} from "react";
type Data={vouchers:any[];accounts:any[];transactions:any[];access:{currentEmail:string;canVoucher:boolean;canPayment:boolean}};
const voucherRoles=new Set(["Voucher administrator","Input-distribution officer","Ministry administrator"]);
const paymentRoles=new Set(["Payment officer","Ministry administrator"]);

export default function Benefits({module,role,notify}:{module:"vouchers"|"payments";role:string;notify:(x:string)=>void}){
  const[data,setData]=useState<Data>({vouchers:[],accounts:[],transactions:[],access:{currentEmail:"",canVoucher:false,canPayment:false}});
  const[modal,setModal]=useState(""); const[selected,setSelected]=useState<any>(null);
  const load=()=>fetch("/api/benefits",{cache:"no-store"}).then(r=>r.json()).then(r=>{if(r)setData({vouchers:Array.isArray(r.vouchers)?r.vouchers:[],accounts:Array.isArray(r.accounts)?r.accounts:[],transactions:Array.isArray(r.transactions)?r.transactions:[],access:r.access||{currentEmail:"tis@totaggroup.com",canVoucher:true,canPayment:true}})}).catch(()=>{});
  useEffect(()=>{load()},[]);
  const manager=module==="vouchers"?Boolean(data?.access?.canVoucher)&&voucherRoles.has(role):Boolean(data?.access?.canPayment)&&paymentRoles.has(role);
  const vchs=Array.isArray(data?.vouchers)?data.vouchers:[];
  const accs=Array.isArray(data?.accounts)?data.accounts:[];
  const txs=Array.isArray(data?.transactions)?data.transactions:[];
  const rows=module==="vouchers"?(manager?vchs:vchs.filter(x=>x.ownerEmail===data?.access?.currentEmail)):(manager?accs:accs.filter(x=>x.ownerEmail===data?.access?.currentEmail));
  const transactions=manager?txs:txs.filter(x=>x.ownerEmail===data?.access?.currentEmail);
  async function send(method:string,body:any){const r=await fetch("/api/benefits",{method,headers:{"content-type":"application/json"},body:JSON.stringify(body)});const j=await r.json();notify(r.ok?"Workflow updated successfully.":j.error||"Action not permitted.");if(r.ok){setModal("");setSelected(null);load()}}
  const submit=(e:FormEvent<HTMLFormElement>,action:string,method="POST")=>{e.preventDefault();send(method,{action,...Object.fromEntries(new FormData(e.currentTarget))})};
  const open=(name:string,item:any=null)=>{setSelected(item);setModal(name)};
  return <div className="benefit-space">
    <section className="benefit-hero"><div><span>{manager?"AUTHORIZED OPERATIONS":"MY BENEFITS"}</span><h2>{module==="vouchers"?(manager?"Voucher issuance & distribution control":"My vouchers and input entitlements"):(manager?"Payment account verification & disbursement control":"My mobile money and payment account")}</h2><p>{module==="vouchers"?(manager?"Issue entitlements and confirm distribution through segregated maker-checker controls.":"View your issued entitlements, collection instructions and receipt history."):(manager?"Verify beneficiary accounts and monitor payment processing.":"Maintain protected payout details, request verification, track payments and report problems.")}</p></div>{(manager&&module==="vouchers")?<button onClick={()=>open("voucher")}>＋ Issue voucher</button>:(!manager&&module==="payments")?<button onClick={()=>open("account")}>＋ Add payout account</button>:(!manager&&module==="vouchers"&&rows.length>0)?<button onClick={()=>open("voucher-issue")}>Report a voucher problem</button>:null}</section>
    {module==="vouchers"?<VoucherTable rows={rows} manager={manager} send={send} open={open}/>:<>
      <article className="panel benefit-table"><header><div><b>{manager?"Beneficiary payout accounts":"My protected payout accounts"}</b><small>Full account numbers are never displayed</small></div>{!manager&&rows.length>0&&<button onClick={()=>open("account")}>＋ Add another account</button>}</header><table><thead><tr><th>DFR ID</th><th>Provider</th><th>Account</th><th>Status</th><th>Permitted actions</th></tr></thead><tbody>{rows.map(a=><tr key={a.id}><td>{a.farmerDfrId}</td><td>{a.provider}<small>{a.accountType}</small></td><td>{a.accountName}<small>{a.accountNumberMasked}</small></td><td>{a.status}</td><td>{manager&&a.status!=="Verified"?<button onClick={()=>send("PATCH",{action:"verify-account",id:a.id,status:"Verified"})}>Verify account</button>:!manager?<div className="benefit-actions"><button onClick={()=>open("edit-account",a)}>Update</button>{!["Verification requested","Verified"].includes(a.status)&&<button onClick={()=>send("PATCH",{action:"request-verification",id:a.id})}>Request verification</button>}</div>:<span>Verified</span>}</td></tr>)}</tbody></table>{!rows.length&&<p className="benefit-empty">No payout account has been added. Add an account to begin verification.</p>}</article>
      <article className="panel benefit-table"><header><div><b>{manager?"Payment transaction monitor":"My payment history and receipts"}</b><small>Programme disbursements, status and failure reasons</small></div>{!manager&&<button onClick={()=>open("payment-issue")}>Report failed or incorrect payment</button>}</header><table><thead><tr><th>Transaction</th><th>Programme</th><th>Amount</th><th>Status</th><th>Receipt / action</th></tr></thead><tbody>{transactions.map(t=><tr key={t.id}><td><code>{t.transactionCode}</code></td><td>{t.programme}</td><td>{t.currency} {Number(t.amount).toFixed(2)}</td><td>{t.status}</td><td>{t.receiptRef?<button onClick={()=>open("receipt",t)}>View receipt</button>:t.failureReason?<><span>{t.failureReason}</span>{!manager&&<button onClick={()=>open("payment-issue",t)}>Report problem</button>}</>:"Processing"}</td></tr>)}</tbody></table>{!transactions.length&&<p className="benefit-empty">No programme payment has been sent to this account. You can still report a missing or expected payment.</p>}</article>
    </>}
    {modal&&<BenefitModal modal={modal} selected={selected} close={()=>{setModal("");setSelected(null)}} submit={submit}/>}
  </div>
}

function VoucherTable({rows,manager,send,open}:{rows:any[];manager:boolean;send:(m:string,b:any)=>void;open:(n:string,i?:any)=>void}){return <article className="panel benefit-table"><header><div><b>{manager?"Authorized voucher register":"Entitlements assigned to me"}</b><small>Farmers cannot issue or self-redeem vouchers</small></div></header><table><thead><tr><th>Voucher</th><th>Programme / entitlement</th><th>Value</th><th>Collection</th><th>Status</th><th>Permitted action</th></tr></thead><tbody>{rows.map(v=><tr key={v.id}><td><code>{v.voucherCode}</code><small>{v.farmerDfrId}</small></td><td>{v.programme}<small>{v.category}</small></td><td>{v.currency} {Number(v.value).toFixed(2)}</td><td>{v.distributionSite}<small>{v.appointmentAt||`Expires ${v.expiresAt}`}</small></td><td>{v.status}</td><td>{manager&&v.status==="Issued"?<button onClick={()=>send("PATCH",{action:"redeem",voucherCode:v.voucherCode})}>Confirm distribution</button>:!manager&&v.status==="Redeemed"&&!v.receiptAcknowledged?<button onClick={()=>send("PATCH",{action:"acknowledge",voucherCode:v.voucherCode})}>Acknowledge receipt</button>:<span>View details</span>}</td></tr>)}</tbody></table>{!rows.length&&<div className="benefit-empty"><b>No voucher is currently assigned to this account.</b><small>If your programme application was approved, notify the voucher team so they can investigate the missing entitlement.</small>{!manager&&<button onClick={()=>open("voucher-issue",{category:"Approved but voucher not issued"})}>I was approved but no voucher was issued</button>}</div>}</article>}

function BenefitModal({modal,selected,close,submit}:{modal:string;selected:any;close:()=>void;submit:(e:FormEvent<HTMLFormElement>,a:string,m?:"POST"|"PATCH")=>void}){
  if(modal==="receipt")return <div className="modal-wrap"><section className="register-modal glass compact-modal receipt-card"><div className="modal-head"><div><span>Official payment record</span><h2>Payment receipt</h2></div><button onClick={close}>×</button></div><dl><div><dt>Transaction</dt><dd>{selected.transactionCode}</dd></div><div><dt>Programme</dt><dd>{selected.programme}</dd></div><div><dt>Amount</dt><dd>{selected.currency} {Number(selected.amount).toFixed(2)}</dd></div><div><dt>Status</dt><dd>{selected.status}</dd></div><div><dt>Receipt reference</dt><dd>{selected.receiptRef}</dd></div><div><dt>Processed</dt><dd>{selected.processedAt||selected.createdAt}</dd></div></dl><div className="modal-actions"><button onClick={close}>Close</button><button onClick={()=>window.print()}>Print / save receipt</button></div></section></div>;
  const edit=modal==="edit-account";const action=edit?"update-account":["voucher-issue","payment-issue"].includes(modal)?"issue":modal;
  return <div className="modal-wrap"><form className="register-modal glass compact-modal" onSubmit={e=>submit(e,action,edit?"PATCH":"POST")}><div className="modal-head"><div><span>Identity-protected workflow</span><h2>{modal==="voucher"?"Issue voucher":modal==="account"?"Add payout account":edit?"Update payout account":modal==="payment-issue"?"Report payment problem":"Report voucher problem"}</h2></div><button type="button" onClick={close}>×</button></div><div className="form-grid">
    {modal==="voucher"&&<><label>Beneficiary email*<input name="ownerEmail" type="email" required/></label><label>DFR ID*<input name="farmerDfrId" required/></label><label>Programme*<input name="programme" required/></label><label>Entitlement*<input name="category" required/></label><label>Value*<input name="value" type="number" required/></label><label>Currency<select name="currency"><option>USD</option><option>LRD</option></select></label><label>Expiry*<input name="expiresAt" type="date" required/></label><label>Distribution site*<input name="distributionSite" required/></label></>}
    {(modal==="account"||edit)&&<><input type="hidden" name="id" value={selected?.id||""}/>{!edit&&<label>DFR ID*<input name="farmerDfrId" required/></label>}<label>Provider*<select name="provider" defaultValue={selected?.provider||"MTN Mobile Money"}><option>MTN Mobile Money</option><option>Orange Money</option><option>Commercial bank</option></select></label><label>Account holder*<input name="accountName" defaultValue={selected?.accountName||""} required/></label><label>New mobile/account number*<input name="accountNumber" required/><small>Re-entry is required; the stored number remains masked.</small></label></>}
    {(modal==="voucher-issue"||modal==="payment-issue")&&<><input type="hidden" name="subjectType" value={modal==="payment-issue"?"Payment":"Voucher"}/><label>{modal==="payment-issue"?"Transaction / programme reference":"Voucher / programme reference"}<input name="subjectRef" defaultValue={selected?.transactionCode||""} placeholder={modal==="payment-issue"?"Enter if available":"Enter voucher code or programme name"}/></label><label>Problem category*<select name="category" defaultValue={selected?.category}>{modal==="payment-issue"?<><option>Expected payment missing</option><option>Payment failed</option><option>Incorrect amount</option><option>Wrong recipient account</option><option>Duplicate payment</option></>:<><option>Approved but voucher not issued</option><option>Voucher not received</option><option>Wrong entitlement</option><option>Distribution problem</option><option>Expired voucher</option></>}</select></label><label className="full-field">Description*<textarea name="description" required/></label></>}
  </div><div className="modal-actions"><button type="button" onClick={close}>Cancel</button><button>Submit →</button></div></form></div>;
}
