"use client";
import { useEffect, useMemo, useState } from "react";
type G=Record<string,any>;
const tabs=["Overview","Dataset stewardship","Validation workflows","Standards & metadata","Sharing agreements","Committee actions","Interoperability","Audit evidence"];
const nextActions:Record<string,[string,string][]>= {SUBMITTED:[["Begin review","UNDER_REVIEW"]],UNDER_REVIEW:[["Request correction","CORRECTION_REQUESTED"],["Approve","APPROVED"]],CORRECTION_REQUESTED:[["Mark resubmitted","RESUBMITTED"]],RESUBMITTED:[["Resume review","UNDER_REVIEW"]],APPROVED:[["Publish","PUBLISHED"]],PUBLISHED:[]};
export default function GovernanceWorkspace({notify}:{notify:(s:string)=>void}){
 const [data,setData]=useState<G>({institutions:[],datasets:[],workflows:[],dictionary:[],agreements:[],decisions:[],exchanges:[],audit:[]});const [institution,setInstitution]=useState("MOA");const [tab,setTab]=useState("Overview");const [busy,setBusy]=useState(0);
 async function load(){setData(await fetch("/api/governance").then(r=>r.json()))}useEffect(()=>{load()},[]);
 const inst=data.institutions.find((x:G)=>x.institutionCode===institution)||{};const queue=data.workflows.filter((x:G)=>x.currentInstitution===institution||x.submitterInstitution===institution);const owned=data.datasets.filter((x:G)=>[x.ownerInstitution,x.stewardInstitution,x.approvingAuthority].some((v:string)=>v?.includes(institution)));const stale=data.datasets.filter((x:G)=>x.nextReviewAt<data.today);
 async function transition(w:G,stage:string){setBusy(w.id);const r=await fetch("/api/governance",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({entityType:"workflow",id:w.id,stage,actor:institution})});setBusy(0);if(r.ok){notify(`${w.caseId} moved to ${stage.replaceAll("_"," ").toLowerCase()} with an audit entry.`);load()}}
 async function review(d:G){setBusy(d.id);await fetch("/api/governance",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({entityType:"dataset",id:d.id,actor:institution})});setBusy(0);notify(`${d.datasetCode} review completed and next review scheduled.`);load()}
 return <div className="gov-space"><section className="gov-hero panel"><div><span>National digital public infrastructure · controlled governance</span><h2>Institutional Governance & Data Stewardship</h2><p>Operational ownership, validation, publication, standards, sharing and institutional accountability across the DFR.</p></div><label>Institution account view<select value={institution} onChange={e=>setInstitution(e.target.value)}>{data.institutions.map((i:G)=><option value={i.institutionCode} key={i.id}>{i.institutionCode} · {i.name}</option>)}</select></label></section>
 <nav className="gov-tabs">{tabs.map(t=><button className={tab===t?"active":""} onClick={()=>setTab(t)} key={t}>{t}</button>)}</nav>
 {tab==="Overview"&&<><div className="metric-grid"><GM n={owned.length} l="Accountable datasets" s="Owner, steward or approver"/><GM n={queue.length} l="Institution cases" s="Submitted or assigned"/><GM n={stale.length} l="Stale reviews" s="Escalation required"/><GM n={data.decisions.filter((x:G)=>x.status!=="Closed").length} l="Open decisions" s="Governance action log"/></div><div className="gov-overview"><article className="panel gov-mandate"><span>{inst.accountRole}</span><h3>{inst.name}</h3><p>{inst.mandate}</p><h4>Content responsibilities</h4><ul>{(inst.contentResponsibilities||[]).map((x:string)=><li key={x}>✓ {x}</li>)}</ul></article><article className="panel"><div className="panel-head"><div><span>Responsibility matrix</span><h3>Dataset accountability</h3></div></div><div className="gov-raci">{data.datasets.map((d:G)=><div key={d.id}><b>{d.datasetCode}</b><span><small>Owner</small>{d.ownerInstitution}</span><span><small>Steward</small>{d.stewardInstitution}</span><span><small>Custodian</small>{d.custodianInstitution}</span><span><small>Approver</small>{d.approvingAuthority}</span></div>)}</div></article></div>{stale.length>0&&<article className="gov-alert panel"><b>⚠ Scheduled-review escalation</b><span>{stale.map((x:G)=>x.title).join(", ")} exceeded the approved review date and requires steward action.</span></article>}</>}
 {tab==="Dataset stewardship"&&<article className="panel registry"><Head a="Controlled data assets" b="Ownership, sensitivity, access, versions and review cycles"/><div className="gov-cards">{data.datasets.map((d:G)=><article key={d.id}><header><code>{d.datasetCode}</code><em className={d.nextReviewAt<data.today?"late":""}>{d.nextReviewAt<data.today?"Review overdue":d.status}</em></header><h3>{d.title}</h3><p>{d.classificationStandard}</p><dl><div><dt>Owner / steward</dt><dd>{d.ownerInstitution} / {d.stewardInstitution}</dd></div><div><dt>Custodian</dt><dd>{d.custodianInstitution}</dd></div><div><dt>Approver</dt><dd>{d.approvingAuthority}</dd></div><div><dt>Sensitivity</dt><dd>{d.sensitivity}</dd></div><div><dt>Version</dt><dd>{d.version}</dd></div><div><dt>Next review</dt><dd>{d.nextReviewAt}</dd></div></dl><footer><span>{d.accessRule}</span><button disabled={busy===d.id} onClick={()=>review(d)}>Complete review</button></footer></article>)}</div></article>}
 {tab==="Validation workflows"&&<article className="panel registry"><Head a="Institutional validation queue" b="Submission → review → correction → approval → publication"/><div className="gov-flow">{data.workflows.map((w:G)=><article key={w.id}><header><code>{w.caseId}</code><em>{w.stage.replaceAll("_"," ")}</em></header><span>{w.workflowType}</span><h3>{w.title}</h3><p>{w.subjectRef} · {w.county} · due {w.dueDate}</p><div className="flow-route"><b>{w.submitterInstitution}</b><i>→</i><b>{w.currentInstitution}</b></div><small>{w.evidenceRef}</small>{w.notes&&<blockquote>{w.notes}</blockquote>}<footer>{(nextActions[w.stage]||[]).map(a=><button disabled={busy===w.id} onClick={()=>transition(w,a[1])} key={a[1]}>{a[0]}</button>)}</footer></article>)}</div></article>}
 {tab==="Standards & metadata"&&<Table title="Version-controlled data dictionary" sub="Official definitions, classifications and allowed values" heads={["Element","Definition","Domain / type","Allowed values","Authority","Version"]} rows={data.dictionary.map((x:G)=>[<code key="c">{x.elementCode}</code>,x.definition,`${x.domain} · ${x.dataType}`,x.allowedValues.join(", "),x.standardOwner,`${x.version} · ${x.status}`])}/>} 
 {tab==="Sharing agreements"&&<Table title="Controlled data-sharing agreements" sub="Purpose limitation, legal basis, access protocol and expiry" heads={["Agreement","Parties","Datasets","Purpose / legal basis","Protection","Status / review"]} rows={data.agreements.map((x:G)=>[<><b>{x.title}</b><small>{x.agreementCode}</small></>,`${x.providerInstitution} → ${x.recipientInstitution}`,x.datasets.join(", "),<>{x.purpose}<small>{x.legalBasis}</small></>,<>{x.sensitivity}<small>{x.accessProtocol}</small></>,<>{x.status}<small>Review {x.reviewDate}</small></>])}/>} 
 {tab==="Committee actions"&&<Table title="Meetings, resolutions and escalations" sub="Institutionally attributed decisions with accountable actions" heads={["Decision","Resolution","Institution","Owner / due","Priority","Status"]} rows={data.decisions.map((x:G)=>[<><b>{x.title}</b><small>{x.decisionCode} · {x.meetingType}</small></>,x.decisionText,x.responsibleInstitution,<>{x.actionOwner}<small>{x.dueDate}</small></>,`${x.priority} · ${x.escalationLevel}`,x.status])}/>} 
 {tab==="Interoperability"&&<Table title="National-system connector catalogue" sub="Mappings and exchange evidence; status distinguishes configuration from live connections" heads={["Connector","Owner / direction","Standard","Environment","Last exchange","Result"]} rows={data.exchanges.map((x:G)=>[<><b>{x.systemName}</b><small>{x.connectorCode} · {x.endpointAlias}</small></>,`${x.ownerInstitution} · ${x.direction}`,`${x.standard} · map ${x.mappingVersion}`,<span className={`status ${x.status.toLowerCase().replaceAll(" ","-")}`}>{x.environment} · {x.status}</span>,x.lastExchangeAt||"No live exchange",<>{x.result}<small>{x.records} records · {x.correlationId}</small></>])}/>} 
 {tab==="Audit evidence"&&<Table title="Cross-institution decision evidence" sub="Attributable actions captured in the platform audit trail" heads={["Timestamp","Actor / institution","Action","Subject","Evidence detail"]} rows={data.audit.map((x:G)=>[x.createdAt,x.actor,x.action,<code key="e">{x.entity}</code>,x.details])}/>} 
 </div>}
function GM({n,l,s}:{n:number;l:string;s:string}){return <article className="metric glass"><div><span>{l}</span><strong>{n}</strong><small>{s}</small></div><i>◈</i></article>}
function Head({a,b}:{a:string;b:string}){return <div className="table-tools"><div><b>{a}</b><span>{b}</span></div></div>}
function Table({title,sub,heads,rows}:{title:string;sub:string;heads:string[];rows:any[][]}){return <article className="panel registry"><Head a={title} b={sub}/><div className="table-wrap"><table><thead><tr>{heads.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((c,j)=><td key={j}>{c}</td>)}</tr>)}</tbody></table></div></article>}
