"use client";
import { FormEvent, useEffect, useState } from "react";

type Programme={programmeCode:string;title:string;description:string;ownerInstitution:string;assistanceType:string;targetGroups:string;counties:string;eligibilityCriteria:string;openingDate:string;deadline:string;status:string};
type Application={applicationCode:string;programmeTitle:string;applicantEmail:string;applicantName:string;applicantRef:string;county:string;district:string;requestedSupport:string;status:string;eligibilityScore:number;reviewer:string;decisionReason:string;submittedAt:string};

const programmeManagerRoles=new Set(["Program officer","Ministry administrator"]);

export default function ProgrammeApplications({role,notify}:{role:string;notify:(message:string)=>void}){
  const [data,setData]=useState<{programmes:Programme[];applications:Application[];access:{role:string;canManage:boolean;scope:string;currentEmail:string}}>({programmes:[],applications:[],access:{role:"Farmer",canManage:false,scope:"Self",currentEmail:""}});
  const [tab,setTab]=useState("programmes"); const [apply,setApply]=useState<Programme|null>(null); const [create,setCreate]=useState(false); const [busy,setBusy]=useState(false);
  const load=()=>fetch("/api/programme-applications",{cache:"no-store"}).then(r=>r.json()).then(r=>{if(r)setData({programmes:Array.isArray(r.programmes)?r.programmes:[],applications:Array.isArray(r.applications)?r.applications:[],access:r.access||{role:"Farmer",canManage:false,scope:"Self",currentEmail:""}})}).catch(()=>{});
  useEffect(()=>{load()},[]);
  async function send(method:string,body:any){setBusy(true);const r=await fetch("/api/programme-applications",{method,headers:{"content-type":"application/json"},body:JSON.stringify(body)});const result=await r.json().catch(()=>({}));setBusy(false);notify(r.ok?"Programme workflow updated successfully.":result.error||"The workflow could not be completed.");if(r.ok){setApply(null);setCreate(false);load()}}
  const submit=(e:FormEvent<HTMLFormElement>,action:string)=>{e.preventDefault();send("POST",{action,...Object.fromEntries(new FormData(e.currentTarget))})};
  const canManage=Boolean(data?.access?.canManage)&&programmeManagerRoles.has(role);
  const apps=Array.isArray(data?.applications)?data.applications:[];
  const visibleApplications=canManage?apps:apps.filter(application=>application.applicantEmail===data?.access?.currentEmail);
  const progs=Array.isArray(data?.programmes)?data.programmes:[];
  return <div className="programme-workspace">
    <div className="programme-banner"><div><span>{canManage?"PROGRAMME OPERATIONS":"FARMER SERVICE ACCESS"}</span><h2>{canManage?"Programme portfolio & application control":"Agricultural support programmes"}</h2><p>{canManage?"Configure opportunities, assess eligibility and record auditable decisions.":"Discover eligible support, submit your own application and follow every decision."}</p></div>{canManage&&<button onClick={()=>setCreate(true)}>＋ Configure programme</button>}</div>
    <div className="programme-tabs"><button className={tab==="programmes"?"active":""} onClick={()=>setTab("programmes")}>Open programmes <b>{progs.filter(p=>p.status==="Open").length}</b></button><button className={tab==="applications"?"active":""} onClick={()=>setTab("applications")}>{canManage?"Application queue":"My applications"} <b>{visibleApplications.length}</b></button></div>
    {tab==="programmes"&&<div className="programme-cards">{progs.map(p=><article key={p.programmeCode}><div><span className={`programme-status ${p.status.toLowerCase()}`}>{p.status}</span><code>{p.programmeCode}</code></div><h3>{p.title}</h3><p>{p.description}</p><dl><div><dt>Assistance</dt><dd>{p.assistanceType}</dd></div><div><dt>Eligible groups</dt><dd>{p.targetGroups}</dd></div><div><dt>Coverage</dt><dd>{p.counties}</dd></div><div><dt>Deadline</dt><dd>{p.deadline}</dd></div></dl><details><summary>Eligibility criteria</summary><p>{p.eligibilityCriteria}</p></details>{!canManage&&p.status==="Open"&&<button onClick={()=>setApply(p)}>Apply for this programme →</button>}</article>)}</div>}
    {tab==="applications"&&<div className="panel programme-table"><table><thead><tr><th>Application</th>{canManage&&<th>Applicant</th>}<th>Programme</th><th>Location</th><th>Status</th><th>Decision / action</th></tr></thead><tbody>{visibleApplications.map(a=><tr key={a.applicationCode}><td><code>{a.applicationCode}</code><small>{new Date(a.submittedAt).toLocaleDateString()}</small></td>{canManage&&<td>{a.applicantName}<small>{a.applicantRef}</small></td>}<td>{a.programmeTitle}<small>{a.requestedSupport}</small></td><td>{a.county}<small>{a.district}</small></td><td><span className="programme-status">{a.status}</span>{a.eligibilityScore>0&&<small>Score {a.eligibilityScore}/100</small>}</td><td>{canManage?<Decision application={a} busy={busy} decide={(body)=>send("PATCH",body)}/>:<><small>{a.decisionReason||"Awaiting authorized review"}</small>{["Submitted","Correction requested"].includes(a.status)&&<button className="link-button" onClick={()=>send("PATCH",{action:"withdraw",applicationCode:a.applicationCode})}>Withdraw</button>}</>}</td></tr>)}</tbody></table>{!visibleApplications.length&&<div className="empty-programmes">No applications are recorded in your authorized scope.</div>}</div>}
    {apply&&<div className="modal-wrap"><form className="register-modal glass compact-modal" onSubmit={e=>submit(e,"apply")}><div className="modal-head"><div><span>Authenticated applicant submission</span><h2>{apply.title}</h2></div><button type="button" onClick={()=>setApply(null)}>×</button></div><input type="hidden" name="programmeCode" value={apply.programmeCode}/><div className="form-grid"><label>DFR / household / organization ID*<input name="applicantRef" required/></label><label>County*<input name="county" required/></label><label>District*<input name="district" required/></label><label className="full-field">Requested support*<textarea name="requestedSupport" required/></label><label className="full-field">Need and expected outcome*<textarea name="justification" required/></label></div><div className="modal-actions"><button type="button" onClick={()=>setApply(null)}>Cancel</button><button disabled={busy}>{busy?"Submitting…":"Submit application →"}</button></div></form></div>}
    {create&&<div className="modal-wrap"><form className="register-modal glass compact-modal" onSubmit={e=>submit(e,"programme")}><div className="modal-head"><div><span>Programme officer control</span><h2>Configure support programme</h2></div><button type="button" onClick={()=>setCreate(false)}>×</button></div><div className="form-grid"><label>Programme title*<input name="title" required/></label><label>Owner institution*<input name="ownerInstitution" defaultValue="Ministry of Agriculture" required/></label><label>Assistance type*<input name="assistanceType" required/></label><label>Target groups*<input name="targetGroups" required/></label><label>Coverage*<input name="counties" defaultValue="National" required/></label><label>Opening date*<input type="date" name="openingDate" required/></label><label>Deadline*<input type="date" name="deadline" required/></label><label className="full-field">Description*<textarea name="description" required/></label><label className="full-field">Eligibility criteria*<textarea name="eligibilityCriteria" required/></label></div><div className="modal-actions"><button type="button" onClick={()=>setCreate(false)}>Cancel</button><button disabled={busy}>{busy?"Saving…":"Save controlled draft →"}</button></div></form></div>}
  </div>
}

function Decision({application,busy,decide}:{application:Application;busy:boolean;decide:(body:any)=>void}){const [status,setStatus]=useState(application.status);const [score,setScore]=useState(application.eligibilityScore);const [reason,setReason]=useState(application.decisionReason);return <div className="decision-controls"><select value={status} onChange={e=>setStatus(e.target.value)}><option>Under review</option><option>Correction requested</option><option>Eligible</option><option>Approved</option><option>Waitlisted</option><option>Rejected</option></select><input aria-label="Eligibility score" type="number" min="0" max="100" value={score} onChange={e=>setScore(+e.target.value)}/><input aria-label="Decision reason" placeholder="Reason / correction" value={reason} onChange={e=>setReason(e.target.value)}/><button disabled={busy} onClick={()=>decide({action:"decision",applicationCode:application.applicationCode,status,eligibilityScore:score,decisionReason:reason})}>Record</button></div>}
