"use client";
import {FormEvent,useState} from "react";

const classes=[
 {id:"individual",title:"Individual Farmer",sub:"Independent producer",icon:"♙"},
 {id:"smallholder",title:"Smallholder / Subsistence",sub:"Family farm under 5 ha",icon:"♧"},
 {id:"farm-worker",title:"Farm Worker",sub:"Permanent, seasonal or outgrower worker",icon:"♟"},
 {id:"household-representative",title:"Household Representative",sub:"Authorized agricultural household contact",icon:"⌂"}
];
const stages=["Entity & Identity","Value-Chain & MoA","Location","Infrastructure, Market & Tools","Household / Staff","Payment & Review"];
const counties=["Bomi","Bong","Gbarpolu","Grand Bassa","Grand Cape Mount","Grand Gedeh","Grand Kru","Lofa","Margibi","Maryland","Montserrado","Nimba","River Cess","River Gee","Sinoe"];
const districts:Record<string,string[]>={Bomi:["Commonwealth","Klay","Mecca","Senjeh"],Bong:["Fuamah","Jorquelleh","Kokoyah","Panta","Salala","Suakoko","Zota"],Gbarpolu:["Belleh","Bokomu","Bopolu","Gbarma","Kongba"],"Grand Bassa":["District 1","District 2","District 3","District 4","Neekreen","Owensgrove","St. John River"],"Grand Cape Mount":["Garwula","Gola Konneh","Porkpa","Tewor"],"Grand Gedeh":["Gbarzon","Gbao","Konobo","Tchien"],"Grand Kru":["Barclayville","Buah","Dorbor","Garraway","Sasstown"],Lofa:["Foya","Kolahun","Quardu Gboni","Salayea","Voinjama","Zorzor"],Margibi:["Firestone","Gibi","Kakata","Mambah-Kaba"],Maryland:["Barrobo","Harper","Karlway","Pleebo-Sodoken"],Montserrado:["Careysburg","Greater Monrovia","St. Paul River","Todee"],Nimba:["Buu-Yao","Doe","Garr Bain","Gbehlay-Geh","Gbor","Sanniquellie-Mahn","Twan River","Yarmein"],"River Cess":["Central River Cess","Doedain","Fen River","Jo River","Norwein"],"River Gee":["Chedepo","Gbeapo","Glaro","Karforh","Potupo","Webbo"],Sinoe:["Butaw","Dugbe River","Greenville","Jaedae","Juarzon","Kpayan","Sanquin 1"]};
const cropGroups=["Crop Farming","Livestock","Aquaculture","Agro-Forestry","Mixed Farming"];
const crops=["Lowland Paddy Rice","Upland Seed Rice","Cassava","Maize / Corn","Yam & Sweet Potato","Plantain & Banana","Soya Beans","Vegetables & Horticulture","Cocoa","Coffee","Oil Palm","Rubber","Livestock","Fisheries"];
const vegetables=["Scotch Bonnet Pepper","Sweet Pepper","Carrot","Cucumber","Bitterball","Okra","Tomato","Eggplant","Cabbage","Watermelon","Leafy Greens (Plassas)"];
const tools=["Cutlasses & Hoes","Motorized Knapsack Sprayer","Power Tiller","Tractor","Grain Thresher","Solar Irrigation Pump","Rice Mill","Cassava Gari Press","Cold Room","Solar Dryer"];

export default function RegistrationWizard({close,notify,refresh,initialKind="individual"}:{close:()=>void;notify:(s:string)=>void;refresh:()=>Promise<void>;initialKind?:string}){
 const normalizedKind=initialKind==="household"?"household-representative":initialKind;
 const [step,setStep]=useState(1),[kind,setKind]=useState(normalizedKind),[county,setCounty]=useState("Bomi"),[draft,setDraft]=useState<Record<string,string>>({}),[busy,setBusy]=useState(false);
 const entity=classes.find(x=>x.id===kind)!;
 const field=(name:string,value:string)=>setDraft(d=>({...d,[name]:value}));
 const capture=()=>navigator.geolocation?.getCurrentPosition(p=>setDraft(d=>({...d,latitude:p.coords.latitude.toFixed(6),longitude:p.coords.longitude.toFixed(6)})),()=>notify("Location permission was not available. Enter coordinates manually."));
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);const payload={firstName:draft.firstName,lastName:draft.lastName,gender:draft.gender||"Female",phone:draft.phone,county,district:draft.district||districts[county][0],community:draft.community,crop:draft.primaryCrop||"Multi-commodity",farmSize:draft.farmSize||0,vulnerability:draft.socialInclusion||"Standard",roadAccess:draft.roadAccess,roadCondition:draft.roadCondition,roadSeasonality:draft.roadSeasonality,roadDistanceMiles:draft.roadDistanceMiles,processingAccess:draft.processingAccess,processingFacilityType:draft.processingFacilityType,processingFacilityName:draft.processingFacilityName,processingFacilityStatus:draft.processingFacilityStatus,processingDistanceMiles:draft.processingDistanceMiles,processingTravelMinutes:draft.processingTravelMinutes,processingTransportMode:draft.processingTransportMode,marketAccess:draft.marketAccess,marketDistanceKm:draft.marketDistanceKm,marketTravelMinutes:draft.marketTravelMinutes,storageAccess:draft.storageAccess,storageCapacityMt:draft.storageCapacityMt,postHarvestLossPct:draft.postHarvestLossPct,transportMode:draft.transportMode,transportOwnership:draft.transportOwnership,tillageMechanization:draft.tillageMechanization,irrigationAccess:draft.irrigationAccess,smartTechReadiness:draft.smartTechReadiness,latitude:draft.latitude,longitude:draft.longitude,dateOfBirth:draft.dateOfBirth,nationalId:draft.nationalId,classification:kind};
  const r=await fetch("/api/farmers",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const b=await r.json();setBusy(false);if(!r.ok){notify(b.error||"Registration could not be completed.");return}notify(`${b.dfrId} registered and queued for verification.`);await refresh();close()}
 return <div className="modal-wrap enrollment-overlay"><form className="enrollment-wizard" onSubmit={submit} onChange={e=>{const x=e.target as HTMLInputElement|HTMLSelectElement;if(!x.name)return;if(x.type==="checkbox"){const values=Array.from(e.currentTarget.querySelectorAll<HTMLInputElement>(`input[name="${x.name}"]:checked`)).map(i=>i.value);field(x.name,values.join(", "))}else field(x.name,x.value)}}>
  <header><div><span>♢ &nbsp; NATIONAL FARMER, HOUSEHOLD & FARM ENROLLMENT</span><h2>Farmer Registration & Farm Profile Wizard</h2><p>Individual-tailored registration for farmers, farm workers, agricultural households, farms and parcels.</p></div><b>Step {step} of 6</b><button type="button" onClick={close}>×</button><nav>{stages.map((s,i)=><button type="button" key={s} className={step===i+1?"active":step>i+1?"done":""} onClick={()=>setStep(i+1)}>{i+1}. {s}</button>)}</nav></header>
  <main>
   {step===1&&<><Panel title="Individual & Household Classification"><div className="classification-grid">{classes.map(c=><label className={kind===c.id?"selected":""} key={c.id}><input type="radio" name="classification" value={c.id} checked={kind===c.id} onChange={()=>setKind(c.id)}/><i>{c.icon}</i><b>{c.title}</b><span>{c.sub}</span></label>)}</div></Panel><IndividualIdentity kind={kind}/><Panel title="Social Inclusion & Vulnerability Classifications"><div className="inclusion-grid"><Check name="socialInclusion" value="Female-Headed Household"/><Check name="socialInclusion" value="Youth Farmer (under 35 years)"/><Check name="socialInclusion" value="Person with Disability"/><Check name="socialInclusion" value="Elderly Farmer (60+ years)"/><Check name="socialInclusion" value="Internally Displaced / Returnee"/><Check name="socialInclusion" value="Extremely Poor / Social Registry Household"/></div></Panel></>}
   {step===2&&<><Panel title="Type of Agriculture (Select All That Apply)"><div className="choice-row">{cropGroups.map(x=><Check name="agricultureTypes" value={x} key={x}/>)}</div></Panel><h3>Primary Commodity and Value Chains</h3><div className="check-grid">{crops.map(x=><Check name="commodities" value={x} key={x}/>)}</div><Panel title="Vegetables & Horticulture — Specify Exact Crops"><div className="check-grid vegetables">{vegetables.map(x=><Check name="vegetables" value={x} key={x}/>)}</div></Panel><label className="full-label">Other specialty commodity<input name="otherCommodity" placeholder="Ginger, turmeric, honey, tree crops…"/></label><Panel title="Ministry of Agriculture Accreditation Status"><div className="radio-line"><label><input type="radio" name="moaAccredited" value="Yes"/> Yes, accredited</label><label><input type="radio" name="moaAccredited" value="No / Pending" defaultChecked/> No / Pending accreditation</label></div></Panel></>}
   {step===3&&<><h3>⌖ Geographic Location (15 Liberian Counties)</h3><div className="enroll-grid three"><label>County*<select name="county" value={county} onChange={e=>setCounty(e.target.value)}>{counties.map(c=><option key={c}>{c}</option>)}</select></label><label>District*<select name="district">{districts[county].map(d=><option key={d}>{d}</option>)}</select></label><label>Clan / Township<input name="township"/></label><label>Community / City*<input name="community" required/></label><label>Village / Local Settlement<input name="village"/></label></div><Panel title="GPS Centroid Coordinates"><button type="button" className="gps-button" onClick={capture}>⌖ Capture Current GPS Location</button><div className="enroll-grid"><label>Latitude (N)<input name="latitude" value={draft.latitude||""} onChange={e=>field("latitude",e.target.value)} placeholder="e.g. 8.3512"/></label><label>Longitude (W)<input name="longitude" value={draft.longitude||""} onChange={e=>field("longitude",e.target.value)} placeholder="e.g. -10.2245"/></label></div></Panel><Panel title="Farm / Parcel Profile"><div className="enroll-grid three"><label>Total farm area (ha)*<input name="farmSize" type="number" step=".01" required/></label><label>Land tenure<select name="landTenure"><option>Customary ownership</option><option>Private deed</option><option>Lease agreement</option><option>Government concession</option><option>Communal land</option></select></label><label>Number of parcels<input name="parcelCount" type="number" min="1"/></label></div></Panel></>}
    {step===4&&<><Panel title="1. Financial Assistance & Intervention Grants"><div className="choice-row"><Check name="assistance" value="Grant only"/><Check name="assistance" value="Loan only"/><Check name="assistance" value="Both grant and loan"/><Check name="assistance" value="No assistance"/></div><h4>Assisting entities & donor programmes</h4><div className="check-grid">{["FAO","MoA STAR-P / REDISSE","World Bank / IFAD","USAID / Feed the Future","AfDB","Commercial bank / MFI","Cooperative / NGO partner","Other"].map(x=><Check name="supportProviders" value={x} key={x}/>)}</div><div className="enroll-grid"><label>Total assistance amount (USD)<input name="assistanceAmount" type="number"/></label><label>Disbursement year<input name="assistanceYear" type="number"/></label></div></Panel>

<Panel title="2. Farm-to-Market Road Connectivity & Accessibility"><div className="enroll-grid three"><label>Road access at farm gate<select name="roadAccess"><option>Direct motorable access</option><option>Footpath to nearest road</option><option>Water transport only</option><option>No practical access</option></select></label><label>Road surface / condition<select name="roadCondition"><option>Paved / all-weather</option><option>Laterite / gravel — good</option><option>Laterite / gravel — poor</option><option>Earth track / mud path</option><option>No road</option></select></label><label>Seasonal passability<select name="roadSeasonality"><option>Year-round passable</option><option>Seasonal / dry season only</option><option>Frequently cut off in rains</option></select></label><label>Distance to nearest motorable road (miles)<input name="roadDistanceMiles" type="number" min="0" step=".1" placeholder="0 if road reaches gate"/></label><label>Distance equivalent (km)<input value={draft.roadDistanceMiles?(Number(draft.roadDistanceMiles)*1.60934).toFixed(2):""} readOnly placeholder="Calculated automatically"/></label><label>Critical road bottleneck<select name="roadBottleneck"><option>None / passable</option><option>Broken bridge / culvert</option><option>Seasonal swamp / waterlogging</option><option>River crossing (canoe only)</option></select></label></div></Panel>

<Panel title="3. Market Access & Commercial Integration"><div className="enroll-grid three"><label>Primary sales outlet / market channel<select name="marketAccess"><option>Periodic rural weekly market (Luma)</option><option>Farmgate buyer / itinerant aggregator</option><option>District / County urban central market</option><option>Contract off-taker / commercial processor</option><option>Institutional buyer (WFP / MoA School Feeding)</option><option>Direct retail / roadside stall</option></select></label><label>Distance to primary market (km)<input name="marketDistanceKm" type="number" min="0" step=".1" placeholder="e.g. 5.5"/></label><label>Travel time to market (minutes)<input name="marketTravelMinutes" type="number" min="0" placeholder="e.g. 45"/></label><label>Market price information source<select name="marketInfoSource"><option>Community radio / word of mouth</option><option>MoA / e-Platform SMS price alerts</option><option>Traders at farmgate</option><option>Extension agent / cooperative</option><option>None / no price access</option></select></label><label>Weekly market day (Luma day)<input name="marketDay" placeholder="e.g. Tuesday, Friday"/></label><label>Nearest commercial trading town<input name="marketTown" placeholder="e.g. Ganta, Foya, Voinjama, Pleebo"/></label></div></Panel>

<Panel title="4. Post-Harvest Storage, Cold Chain & Agro-Processing"><div className="enroll-grid three"><label>Storage facility available<select name="storageAccess"><option>None / Immediate distress sale at harvest</option><option>Hermetic storage (PICS bags / sealed drums)</option><option>Traditional crib / thatch granary</option><option>Community / Cooperative shared warehouse</option><option>Solar drying floor / parabolic drying shed</option><option>Temperature-controlled cold room / packhouse</option></select></label><label>Dedicated storage capacity (Metric Tons)<input name="storageCapacityMt" type="number" min="0" step=".1" placeholder="e.g. 1.0"/></label><label>Estimated post-harvest loss (%)<input name="postHarvestLossPct" type="number" min="0" max="100" placeholder="e.g. 15%"/></label><label>Processing facility access<select name="processingAccess"><option value="On-farm facility">Facility located on this farm</option><option value="Nearby external facility">Uses / can access a nearby facility</option><option value="Facility unavailable">No accessible processing facility</option></select></label><label>Facility type<select name="processingFacilityType"><option>Rice mill / de-stoner</option><option>Cassava processing / gari press</option><option>Cocoa fermentation / dryer</option><option>Palm oil mill / digester</option><option>Cold room / packhouse</option><option>Feed mill</option><option>Fish smoking / cold storage</option><option>Multi-purpose facility</option><option>Other</option></select></label><label>Facility operational status<select name="processingFacilityStatus"><option>Fully operational</option><option>Partly operational</option><option>Seasonal operation</option><option>Non-operational / needs repair</option><option>Planned / under construction</option></select></label><label>Facility name / operator<input name="processingFacilityName" placeholder="e.g. Gbedin Rice Mill Hub"/></label><label>Distance to facility (miles)<input name="processingDistanceMiles" type="number" min="0" step=".1"/></label><label>Transit time to facility (minutes)<input name="processingTravelMinutes" type="number" min="0"/></label></div></Panel>

<Panel title="5. Produce Haulage & Transport Logistics"><div className="enroll-grid three"><label>Primary mode of produce transport<select name="transportMode"><option>Motorbike / Kehkeh (Tricycle)</option><option>Head-loading / Porterage</option><option>Light pickup truck / 4WD (1–3 MT)</option><option>Heavy commercial truck (&gt; 5 MT)</option><option>Water canoe / motorized boat</option><option>Bicycle / Handcart</option></select></label><label>Transport vehicle ownership<select name="transportOwnership"><option>Hired commercial transporter</option><option>Self-owned vehicle / motorbike</option><option>Cooperative / Group shared asset</option><option>Buyer-provided collection at farmgate</option></select></label><label>Average haulage cost per bag/trip (LRD or USD)<input name="transportCost" placeholder="e.g. 350 LRD or $2.50 USD"/></label></div></Panel>

<Panel title="6. Agricultural Mechanization, Irrigation & Smart Farming Infrastructure"><div className="enroll-grid three"><label>Tillage mechanization level<select name="tillageMechanization"><option>Manual hand tools (cutlass, hoe)</option><option>Power tiller / 2-wheel walking tractor</option><option>4-wheel commercial tractor (rented / hired)</option><option>4-wheel commercial tractor (owned)</option><option>Animal traction / draft oxen</option></select></label><label>Irrigation water infrastructure<select name="irrigationAccess"><option>Rainfed only</option><option>Manual watering can / bucket from stream or well</option><option>Solar-powered surface / submersible pump</option><option>Motorized petrol / diesel water pump</option><option>Gravity-fed canal / lowland swamp water control</option><option>Drip or sprinkler irrigation scheme</option></select></label><label>Digital &amp; smart tech readiness<select name="smartTechReadiness"><option>Basic 2G feature phone (SMS / Voice)</option><option>Smartphone with GPS &amp; camera</option><option>Digital soil testing kit / NPK probe</option><option>On-farm rain gauge / micro weather station</option><option>Digital farm management app / recordbook</option><option>None / No phone access</option></select></label></div><h4 style={{marginTop:"14px",marginBottom:"8px"}}>Operating farm tools &amp; equipment owned</h4><div className="check-grid">{tools.map(x=><Check name="tools" value={x} key={x}/>)}</div></Panel></>}
   {step===5&&<><h3>♧ Farmer Household & Labour Profile</h3><Panel title="Household Composition"><div className="enroll-grid three"><label>Household size<input name="householdSize" type="number"/></label><label>Women in household<input name="householdWomen" type="number"/></label><label>Youth in household<input name="householdYouth" type="number"/></label><label>Permanent farm workers<input name="permanentEmployees" type="number"/></label><label>Seasonal farm workers<input name="seasonalWorkers" type="number"/></label><label>Persons with disability<input name="pwdCount" type="number"/></label></div></Panel></>}
   {step===6&&<><h3>▭ Mobile Money Account & Final Review</h3><div className="enroll-grid three"><label>Mobile money provider<select name="mobileProvider"><option>MTN Mobile Money Liberia</option><option>Orange Money Liberia</option><option>Bank account</option><option>No account</option></select></label><label>Payment phone / account number<input name="paymentAccount"/></label><label>Account holder name<input name="accountHolder"/></label></div><div className="review-card"><h4>Registration Profile Summary & Verification Preview</h4><div><p><span>Entity classification</span><b>{entity.title}</b></p><p><span>Primary name</span><b>{draft.legalName||`${draft.firstName||"—"} ${draft.lastName||""}`}</b></p><p><span>Location</span><b>{county} ({draft.district||districts[county][0]})</b></p><p><span>MoA accredited</span><b>{draft.moaAccredited||"No / Pending"}</b></p></div></div><label className="consent"><input type="checkbox" required/> I confirm authority, informed consent and accuracy of this registration for authorized government service delivery.</label></>}
  </main><footer><button type="button" disabled={step===1} onClick={()=>setStep(step-1)}>← Previous Step</button>{step<6?<button type="button" onClick={()=>setStep(step+1)}>Next Step →</button>:<button className="submit-registration" disabled={busy}>{busy?"Submitting securely…":"Submit Official Registration"}</button>}</footer>
 </form></div>
}
function Panel({title,children}:{title:string;children:React.ReactNode}){return <section className="enroll-panel"><h3>{title}</h3>{children}</section>}
function Check({name,value}:{name:string;value:string}){return <label className="check-choice"><input type="checkbox" name={name} value={value}/><b>{value}</b></label>}
function IndividualIdentity({kind}:{kind:string}){return <section className="identity-panel"><h3>♙ {kind==="smallholder"?"Smallholder / Subsistence Farmer Identity":"Individual Farmer Identity Details"}</h3><div className="enroll-grid three"><label>First name*<input name="firstName" required/></label><label>Middle name<input name="middleName"/></label><label>Last name*<input name="lastName" required/></label><label>Date of birth<input name="dateOfBirth" type="date"/></label><label>Sex<select name="gender"><option>Female</option><option>Male</option><option>Other</option></select></label><label>National ID (NIN / Voter ID)<input name="nationalId"/></label><label>Phone<input name="phone"/></label></div></section>}
