import { desc, eq } from "drizzle-orm";
import { NextRequest, NextResponse } from "next/server";
import { getDb } from "../../../db";
import { accessAssignments, auditEvents, helpTicketMessages, helpTickets, knowledgeArticles } from "../../../db/schema";
import { getChatGPTUser } from "../../chatgpt-auth";

export const dynamic = "force-dynamic";
const managers = new Set(["Help-desk officer","System administrator","Ministry administrator"]);
const transitions:Record<string,string[]>={Open:["Acknowledged","In progress","Closed"],Acknowledged:["In progress","Waiting for user","Resolved"],"In progress":["Waiting for user","Resolved"],"Waiting for user":["In progress","Resolved"],Resolved:["Closed","In progress"],Closed:["In progress"]};
const articles=[
  ["KB-001","Registering a farmer or organization","Registration","Use the single Registration button to open the entity-tailored wizard.","Select the correct entity type, complete each required step, record consent, validate the location and submit. A provisional number is issued until approval."],
  ["KB-002","Correcting a submitted record","Registration / data correction","Request a controlled correction without creating a duplicate record.","Open a Help Desk request, select Registration / data correction, include the provisional or DFR ID, describe the field to correct and attach no unnecessary sensitive information."],
  ["KB-003","Recovering an offline submission","Offline synchronization","Resolve records that remain in the device synchronization queue.","Confirm connectivity, open Offline Sync and retry. If the record still fails, provide the device reference and error time in a Technical error ticket."],
  ["KB-004","Reporting a payment or voucher issue","Programme / payment","Route service-delivery exceptions to the correct operational team.","Do not include a PIN or password. Provide the DFR ID, programme, transaction reference and date. Restricted payment details remain access-controlled."],
];

async function ctx(){const user=await getChatGPTUser();if(!user)return null;const db=await getDb();const assignment=(await db.select().from(accessAssignments).where(eq(accessAssignments.email,user.email)).limit(1))[0];const role=assignment?.role||"Farmer";return{db,user,assignment,role,canManage:managers.has(role)}}
async function seed(c:NonNullable<Awaited<ReturnType<typeof ctx>>>){if(!(await c.db.select({id:knowledgeArticles.id}).from(knowledgeArticles).limit(1)).length)await c.db.insert(knowledgeArticles).values(articles.map(a=>({articleCode:a[0],title:a[1],category:a[2],summary:a[3],content:a[4]})));}
function fail(error:string,status=400){return NextResponse.json({error},{status})}
function due(hours:number){return new Date(Date.now()+hours*3600000).toISOString()}
function sla(priority:string){return priority==="Critical"?4:priority==="High"?8:priority==="Low"?72:24}

export async function GET(){const c=await ctx();if(!c)return fail("Sign in required",401);await seed(c);const rows=c.canManage?await c.db.select().from(helpTickets).orderBy(desc(helpTickets.updatedAt)):await c.db.select().from(helpTickets).where(eq(helpTickets.requesterEmail,c.user.email)).orderBy(desc(helpTickets.updatedAt));const msgs=await c.db.select().from(helpTicketMessages).orderBy(helpTicketMessages.createdAt);const safeMessages=msgs.filter(m=>m.visibility!=="Internal"||c.canManage);const kb=await c.db.select().from(knowledgeArticles).where(eq(knowledgeArticles.status,"Published")).orderBy(knowledgeArticles.category);return NextResponse.json({tickets:rows.map(t=>({...t,messages:safeMessages.filter(m=>m.ticketCode===t.ticketCode)})),articles:kb,access:{role:c.role,canManage:c.canManage,institution:c.assignment?.institution||"Citizen / farmer"}})}

export async function POST(req:NextRequest){const c=await ctx();if(!c)return fail("Sign in required",401);const b=await req.json();if(b.action==="message")return message(c,b);if(!String(b.subject||"").trim()||!String(b.description||"").trim())return fail("Subject and description are required");const priority=["Low","Normal","High","Critical"].includes(b.priority)?b.priority:"Normal";const hours=sla(priority);const code=`HD-${new Date().getUTCFullYear()}-${crypto.randomUUID().slice(0,6).toUpperCase()}`;await c.db.insert(helpTickets).values({ticketCode:code,requesterEmail:c.user.email,requesterName:c.user.displayName,requesterRole:String(b.requesterRole||c.role),institution:c.assignment?.institution||"Citizen / farmer",county:String(b.county||"National"),subject:String(b.subject).trim(),category:String(b.category||"General support"),channel:String(b.channel||"In-platform"),description:String(b.description).trim(),priority,sensitivity:String(b.sensitivity||"Internal"),slaHours:hours,dueAt:due(hours)});await c.db.insert(helpTicketMessages).values({ticketCode:code,authorEmail:c.user.email,authorName:c.user.displayName,authorRole:c.role,message:String(b.description).trim()});await c.db.insert(auditEvents).values({actor:c.user.email,action:"HELP_TICKET_CREATED",entity:code,details:`${priority} · ${b.category||"General support"}`});return NextResponse.json({ok:true,ticketCode:code},{status:201})}

async function message(c:NonNullable<Awaited<ReturnType<typeof ctx>>>,b:any){const t=(await c.db.select().from(helpTickets).where(eq(helpTickets.ticketCode,String(b.ticketCode))).limit(1))[0];if(!t)return fail("Ticket not found",404);if(!c.canManage&&t.requesterEmail!==c.user.email)return fail("Not authorized",403);if(!String(b.message||"").trim())return fail("Message is required");const visibility=b.visibility==="Internal"&&c.canManage?"Internal":"Requester-visible";await c.db.insert(helpTicketMessages).values({ticketCode:t.ticketCode,authorEmail:c.user.email,authorName:c.user.displayName,authorRole:c.role,message:String(b.message).trim(),visibility});await c.db.update(helpTickets).set({updatedAt:new Date().toISOString(),status:!c.canManage&&t.status==="Waiting for user"?"In progress":t.status}).where(eq(helpTickets.ticketCode,t.ticketCode));await c.db.insert(auditEvents).values({actor:c.user.email,action:visibility==="Internal"?"HELP_INTERNAL_NOTE":"HELP_TICKET_MESSAGE",entity:t.ticketCode,details:"Support conversation updated"});return NextResponse.json({ok:true})}

export async function PATCH(req:NextRequest){const c=await ctx();if(!c)return fail("Sign in required",401);const b=await req.json();const t=(await c.db.select().from(helpTickets).where(eq(helpTickets.ticketCode,String(b.ticketCode))).limit(1))[0];if(!t)return fail("Ticket not found",404);if(!c.canManage){if(t.requesterEmail!==c.user.email)return fail("Not authorized",403);if(b.action==="rate"){const n=Math.max(1,Math.min(5,Number(b.satisfaction)));await c.db.update(helpTickets).set({satisfaction:n,updatedAt:new Date().toISOString()}).where(eq(helpTickets.ticketCode,t.ticketCode));return NextResponse.json({ok:true})}if(b.action==="reopen"&&["Resolved","Closed"].includes(t.status)){await c.db.update(helpTickets).set({status:"In progress",resolvedAt:"",updatedAt:new Date().toISOString()}).where(eq(helpTickets.ticketCode,t.ticketCode));return NextResponse.json({ok:true})}return fail("Only support staff may manage ticket workflow",403)}
 const next=String(b.status||t.status);if(next!==t.status&&!transitions[t.status]?.includes(next))return fail(`Invalid transition: ${t.status} → ${next}`);if(next==="Resolved"&&!String(b.resolution||t.resolution).trim())return fail("A resolution is required before resolving the ticket");await c.db.update(helpTickets).set({status:next,assignedTeam:String(b.assignedTeam||t.assignedTeam),assignedTo:String(b.assignedTo||t.assignedTo),priority:String(b.priority||t.priority),resolution:String(b.resolution??t.resolution),resolvedAt:next==="Resolved"?new Date().toISOString():next==="In progress"?"":t.resolvedAt,updatedAt:new Date().toISOString()}).where(eq(helpTickets.ticketCode,t.ticketCode));await c.db.insert(auditEvents).values({actor:c.user.email,action:"HELP_TICKET_WORKFLOW_UPDATED",entity:t.ticketCode,details:`${t.status} → ${next}; ${b.assignedTeam||t.assignedTeam}; ${b.assignedTo||t.assignedTo}`});return NextResponse.json({ok:true})}
