import {and,desc,eq} from "drizzle-orm";import{NextRequest,NextResponse}from"next/server";import{getDb}from"../../../db";import{accessAssignments,auditEvents,grievanceEvents,grievances}from"../../../db/schema";import{getChatGPTUser}from"../../chatgpt-auth";
export const dynamic="force-dynamic";const officers=new Set(["Help-desk officer","Verification officer","Program officer","County agricultural officer","District agricultural officer","Ministry administrator"]);
async function context(){const user=await getChatGPTUser();if(!user)return null;const db=await getDb();const assignment=(await db.select().from(accessAssignments).where(eq(accessAssignments.email,user.email)).limit(1))[0]||null;const caps:string[]=assignment?JSON.parse(assignment.capabilities||"[]"):[];const role=assignment?.role||"Farmer";return{db,user,role,assignment,canManage:assignment?.status==="Active"&&(officers.has(role)||caps.includes("grievance.manage"))}}
export async function GET(){const c=await context();if(!c)return NextResponse.json({error:"Authentication required"},{status:401});let cases=c.canManage?await c.db.select().from(grievances).orderBy(desc(grievances.createdAt)):await c.db.select().from(grievances).where(eq(grievances.ownerEmail,c.user.email)).orderBy(desc(grievances.createdAt));if(c.canManage&&c.assignment?.countyScope&&c.assignment.countyScope!=="National")cases=cases.filter((x:any)=>x.county===c.assignment.countyScope);return NextResponse.json({cases,access:{role:c.role,currentEmail:c.user.email,canManage:c.canManage,scope:c.assignment?.countyScope||"Self"}})}
export async function POST(req:NextRequest){const c=await context();if(!c)return NextResponse.json({error:"Authentication required"},{status:401});const b=await req.json();if(!b.category||!b.county||!b.description)return NextResponse.json({error:"Complete all required fields"},{status:400});const ticket=`GRV-${Date.now().toString(36).toUpperCase()}`;await c.db.insert(grievances).values({ticketId:ticket,farmerDfrId:String(b.farmerDfrId||"Not supplied"),category:String(b.category),channel:"Web portal",county:String(b.county),description:String(b.description),priority:String(b.priority||"Normal"),ownerEmail:c.user.email,ownerName:c.user.displayName});await c.db.insert(grievanceEvents).values({ticketId:ticket,actorEmail:c.user.email,actorName:c.user.displayName,actorRole:c.role,action:"GRIEVANCE_SUBMITTED",comments:"Submitted by authenticated complainant"});await c.db.insert(auditEvents).values({actor:c.user.email,action:"Grievance submitted",entity:ticket,details:String(b.category)});return NextResponse.json({ok:true,ticket},{status:201})}
export async function PATCH(req:NextRequest){const c=await context();if(!c)return NextResponse.json({error:"Authentication required"},{status:401});const b=await req.json();const ticket=String(b.ticketId);const record=(await c.db.select().from(grievances).where(eq(grievances.ticketId,ticket)).limit(1))[0];if(!record)return NextResponse.json({error:"Case not found"},{status:404});
 if(b.action==="withdraw"){if(record.ownerEmail!==c.user.email||!["Open","Submitted"].includes(record.status))return NextResponse.json({error:"Case cannot be withdrawn"},{status:403});await c.db.update(grievances).set({status:"Withdrawn",updatedAt:new Date().toISOString()}).where(eq(grievances.ticketId,ticket));}
 else if(b.action==="decision"){if(!c.canManage)return NextResponse.json({error:"Grievance-management permission required"},{status:403});const allowed=["In review","Information requested","Escalated","Resolved","Closed"];if(!allowed.includes(b.status))return NextResponse.json({error:"Invalid status"},{status:400});await c.db.update(grievances).set({status:String(b.status),assignedTo:c.user.displayName,resolution:String(b.resolution||""),resolvedAt:b.status==="Resolved"?new Date().toISOString():"",updatedAt:new Date().toISOString()}).where(eq(grievances.ticketId,ticket));}
 else return NextResponse.json({error:"Unsupported action"},{status:400});await c.db.insert(grievanceEvents).values({ticketId:ticket,actorEmail:c.user.email,actorName:c.user.displayName,actorRole:c.role,action:String(b.action).toUpperCase(),comments:String(b.resolution||"")});await c.db.insert(auditEvents).values({actor:c.user.email,action:`Grievance ${b.action}`,entity:ticket,details:String(b.status||"")});return NextResponse.json({ok:true})}
